/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 1LHryFzrfagz6s5XszxyaX
// Component: _Cbr6Dwvaf0w
import * as React from "react";
import { useRouter } from "next/router";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import LinkButton from "../../LinkButton"; // plasmic-import: IXlYPJ9laVnz/component
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 1LHryFzrfagz6s5XszxyaX/styleTokensProvider
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic.module.css"; // plasmic-import: 1LHryFzrfagz6s5XszxyaX/projectcss
import sty from "./PlasmicInfoBlockRank.module.css"; // plasmic-import: _Cbr6Dwvaf0w/css
import BadgeCheckIcon from "./icons/PlasmicIcon__BadgeCheck"; // plasmic-import: OE1F_elgA17S/icon

createPlasmicElementProxy;

export const PlasmicInfoBlockRank__VariantProps = new Array();

export const PlasmicInfoBlockRank__ArgProps = new Array();

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicInfoBlockRank__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );
  const $props = {
    ...args,
    ...variants
  };
  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const styleTokensClassNames = _useStyleTokens();
  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.root
      )}
    >
      <div
        data-plasmic-name={"wrap"}
        data-plasmic-override={overrides.wrap}
        className={classNames(projectcss.all, sty.wrap)}
      >
        <div className={classNames(projectcss.all, sty.freeBox__xkcUu)}>
          <div
            data-plasmic-name={"text"}
            data-plasmic-override={overrides.text}
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text
            )}
          >
            {
              "We rank casinos by reputation, bonus clarity, withdrawal speed, and supported payment methods."
            }
          </div>
        </div>
        <div className={classNames(projectcss.all, sty.freeBox___24JXu)}>
          <LinkButton
            data-plasmic-name={"linkButton"}
            data-plasmic-override={overrides.linkButton}
            className={classNames("__wab_instance", sty.linkButton)}
            color={"outlined"}
            href={`/guides/how-to-choose-a-crypto-casino`}
            iconLeft={
              <BadgeCheckIcon
                data-plasmic-name={"svg"}
                data-plasmic-override={overrides.svg}
                className={classNames(projectcss.all, sty.svg)}
                role={"img"}
              />
            }
            showIcon={["left"]}
            size={"medium"}
            title={"How we rank casinos"}
          />
        </div>
      </div>
    </div>
  );
}

const PlasmicDescendants = {
  root: ["root", "wrap", "text", "linkButton", "svg"],
  wrap: ["wrap", "text", "linkButton", "svg"],
  text: ["text"],
  linkButton: ["linkButton", "svg"],
  svg: ["svg"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicInfoBlockRank__ArgProps,
          internalVariantPropNames: PlasmicInfoBlockRank__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicInfoBlockRank__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicInfoBlockRank";
  } else {
    func.displayName = `PlasmicInfoBlockRank.${nodeName}`;
  }
  return func;
}

export const PlasmicInfoBlockRank = Object.assign(
  // Top-level PlasmicInfoBlockRank renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    wrap: makeNodeComponent("wrap"),
    text: makeNodeComponent("text"),
    linkButton: makeNodeComponent("linkButton"),
    svg: makeNodeComponent("svg"),
    // Metadata about props expected for PlasmicInfoBlockRank
    internalVariantProps: PlasmicInfoBlockRank__VariantProps,
    internalArgProps: PlasmicInfoBlockRank__ArgProps
  }
);

export default PlasmicInfoBlockRank;
/* prettier-ignore-end */
