/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 1LHryFzrfagz6s5XszxyaX
// Component: 6YxcbeY1AF1_
import * as React from "react";
import { useRouter } from "next/router";
import {
  PlasmicImg as PlasmicImg__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  hasVariant,
  renderPlasmicSlot
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import LinkButton from "../../LinkButton"; // plasmic-import: IXlYPJ9laVnz/component
import LinkCoinIcon from "../../LinkCoinIcon"; // plasmic-import: q2l6s7HIpw7u/component
import TagPill from "../../TagPill"; // plasmic-import: nn118kQlMOAC/component
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: 1LHryFzrfagz6s5XszxyaX/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 1LHryFzrfagz6s5XszxyaX/styleTokensProvider
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic.module.css"; // plasmic-import: 1LHryFzrfagz6s5XszxyaX/projectcss
import sty from "./PlasmicCardCasinoList.module.css"; // plasmic-import: 6YxcbeY1AF1_/css
import ZapIcon from "./icons/PlasmicIcon__Zap"; // plasmic-import: rZ8hz7v-qc_C/icon
import ShieldCheckIcon from "./icons/PlasmicIcon__ShieldCheck"; // plasmic-import: B8aXAFRTKbUL/icon
import CoinsIcon from "./icons/PlasmicIcon__Coins"; // plasmic-import: YH9P_qiC8MJ-/icon

createPlasmicElementProxy;

export const PlasmicCardCasinoList__VariantProps = new Array();

export const PlasmicCardCasinoList__ArgProps = new Array(
  "logo",
  "position",
  "title",
  "coins"
);

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicCardCasinoList__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(
    () =>
      Object.assign(
        {
          logo: {
            src: "/plasmic/cryptocasinos/images/stakeLogoSvg.svg",
            fullWidth: 447,
            fullHeight: 222,
            aspectRatio: 2.013514
          }
        },
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );
  const $props = {
    ...args,
    ...variants
  };
  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const globalVariants = _useGlobalVariants();
  const styleTokensClassNames = _useStyleTokens();
  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.root,
        "bg-grain"
      )}
    >
      <div className={classNames(projectcss.all, sty.freeBox__oSgaQ)} />
      <div className={classNames(projectcss.all, sty.freeBox__jZcKz)}>
        <div className={classNames(projectcss.all, sty.freeBox___3Iq9C)}>
          <div className={classNames(projectcss.all, sty.freeBox__iH2VG)}>
            <div className={classNames(projectcss.all, sty.freeBox___84Ygu)}>
              {renderPlasmicSlot({
                defaultContents: "#1",
                value: args.position,
                className: classNames(sty.slotTargetPosition)
              })}
            </div>
          </div>
          <PlasmicImg__
            data-plasmic-name={"img"}
            data-plasmic-override={overrides.img}
            alt={""}
            className={classNames(sty.img)}
            displayHeight={"80px"}
            displayMaxHeight={"none"}
            displayMaxWidth={"100%"}
            displayMinHeight={"0"}
            displayMinWidth={"0"}
            displayWidth={"auto"}
            loading={"lazy"}
            src={args.logo}
          />
        </div>
        <div className={classNames(projectcss.all, sty.freeBox__axL9K)}>
          <div className={classNames(projectcss.all, sty.freeBox__nEf7B)}>
            {renderPlasmicSlot({
              defaultContents: "Stake",
              value: args.title,
              className: classNames(sty.slotTargetTitle)
            })}
          </div>
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text___0JSby
            )}
          >
            {"Fast payouts, premium UX, and sportsbook included."}
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__wvjO)}>
            <div className={classNames(projectcss.all, sty.freeBox___7CUkg)}>
              <ZapIcon
                className={classNames(projectcss.all, sty.svg__fbZfz)}
                role={"img"}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__hTnoa
                )}
              >
                {"Instant cashout"}
              </div>
            </div>
            <div className={classNames(projectcss.all, sty.freeBox__kOyok)}>
              <ShieldCheckIcon
                className={classNames(projectcss.all, sty.svg___5VVDo)}
                role={"img"}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__jI51C
                )}
              >
                {"Trusted"}
              </div>
            </div>
            <div className={classNames(projectcss.all, sty.freeBox__vp2F)}>
              <CoinsIcon
                className={classNames(projectcss.all, sty.svg___3Hp5N)}
                role={"img"}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__dp0Jk
                )}
              >
                {"12+ coins"}
              </div>
            </div>
          </div>
        </div>
        <div className={classNames(projectcss.all, sty.freeBox__iZoh2)}>
          <div className={classNames(projectcss.all, sty.freeBox__cyINf)}>
            <LinkButton
              className={classNames("__wab_instance", sty.linkButton___3SGTw)}
              color={"clear"}
              href={`/casinos/stake`}
              size={
                hasVariant(globalVariants, "screen", "mobile")
                  ? "medium"
                  : undefined
              }
              title={"Read Review"}
            />
          </div>
          <div
            className={classNames(
              projectcss.all,
              sty.freeBox__x7Iy0,
              "link-coin-icon-wrap"
            )}
          >
            {renderPlasmicSlot({
              defaultContents: (
                <React.Fragment>
                  <LinkCoinIcon
                    className={classNames(
                      "__wab_instance",
                      sty.linkCoinIcon___6PGpL
                    )}
                    size={"small"}
                  />

                  <LinkCoinIcon
                    className={classNames(
                      "__wab_instance",
                      sty.linkCoinIcon___8R8Xh
                    )}
                    icon={{
                      src: "/plasmic/cryptocasinos/images/coinEthSvg.svg",
                      fullWidth: 225,
                      fullHeight: 225,
                      aspectRatio: 1
                    }}
                    size={"small"}
                  />

                  <LinkCoinIcon
                    className={classNames(
                      "__wab_instance",
                      sty.linkCoinIcon___0I7Pj
                    )}
                    icon={{
                      src: "/plasmic/cryptocasinos/images/coinSolSvg.svg",
                      fullWidth: 225,
                      fullHeight: 225,
                      aspectRatio: 1
                    }}
                    size={"small"}
                  />

                  <LinkCoinIcon
                    className={classNames(
                      "__wab_instance",
                      sty.linkCoinIcon__pXmHc
                    )}
                    icon={{
                      src: "/plasmic/cryptocasinos/images/coinAdaSvg.svg",
                      fullWidth: 225,
                      fullHeight: 225,
                      aspectRatio: 1
                    }}
                    size={"small"}
                  />

                  <LinkCoinIcon
                    className={classNames(
                      "__wab_instance",
                      sty.linkCoinIcon__xkRp
                    )}
                    icon={{
                      src: "/plasmic/cryptocasinos/images/coinDotSvg.svg",
                      fullWidth: 225,
                      fullHeight: 225,
                      aspectRatio: 1
                    }}
                    size={"small"}
                  />
                </React.Fragment>
              ),

              value: args.coins
            })}
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__vKt1X
              )}
            >
              {"+9"}
            </div>
          </div>
        </div>
      </div>
      <div className={classNames(projectcss.all, sty.freeBox__ynhF6)}>
        <div className={classNames(projectcss.all, sty.freeBox___0ZSoz)}>
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__lnf4L
            )}
          >
            {"Welcome bonus"}
          </div>
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__qcjM3
            )}
          >
            {"200% up to $1k"}
          </div>
        </div>
        <div className={classNames(projectcss.all, sty.freeBox__fmD1L)}>
          <TagPill
            className={classNames("__wab_instance", sty.tagPill__xdsC)}
          />

          <TagPill
            className={classNames("__wab_instance", sty.tagPill___2M1Yh)}
            title={"BTC"}
          />

          <TagPill
            className={classNames("__wab_instance", sty.tagPill___2L42P)}
            title={"Non sticky"}
          />
        </div>
        <LinkButton
          className={classNames("__wab_instance", sty.linkButton___00Y9F)}
          size={"medium"}
          title={"Claim Bonus"}
        />
      </div>
    </div>
  );
}

const PlasmicDescendants = {
  root: ["root", "img"],
  img: ["img"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicCardCasinoList__ArgProps,
          internalVariantPropNames: PlasmicCardCasinoList__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicCardCasinoList__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicCardCasinoList";
  } else {
    func.displayName = `PlasmicCardCasinoList.${nodeName}`;
  }
  return func;
}

export const PlasmicCardCasinoList = Object.assign(
  // Top-level PlasmicCardCasinoList renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    img: makeNodeComponent("img"),
    // Metadata about props expected for PlasmicCardCasinoList
    internalVariantProps: PlasmicCardCasinoList__VariantProps,
    internalArgProps: PlasmicCardCasinoList__ArgProps
  }
);

export default PlasmicCardCasinoList;
/* prettier-ignore-end */
