/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 1LHryFzrfagz6s5XszxyaX
// Component: rsu3SXicdqjb
import * as React from "react";
import { useRouter } from "next/router";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  renderPlasmicSlot
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 1LHryFzrfagz6s5XszxyaX/styleTokensProvider
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic.module.css"; // plasmic-import: 1LHryFzrfagz6s5XszxyaX/projectcss
import sty from "./PlasmicInfoDotPanel.module.css"; // plasmic-import: rsu3SXicdqjb/css

createPlasmicElementProxy;

export const PlasmicInfoDotPanel__VariantProps = new Array();

export const PlasmicInfoDotPanel__ArgProps = new Array("content");

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicInfoDotPanel__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );
  const $props = {
    ...args,
    ...variants
  };
  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const styleTokensClassNames = _useStyleTokens();
  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.root
      )}
    >
      <div
        data-plasmic-name={"wrap"}
        data-plasmic-override={overrides.wrap}
        className={classNames(projectcss.all, sty.wrap)}
      >
        {renderPlasmicSlot({
          defaultContents: (
            <React.Fragment>
              <div className={classNames(projectcss.all, sty.freeBox__nLtAn)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___8On2
                  )}
                >
                  {"40+"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__d2NYv
                  )}
                >
                  {"Coins tracked"}
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__nzBbc)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___0ZpUm
                  )}
                >
                  {"Live"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__zTvmR
                  )}
                >
                  {"Market data"}
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__o6Buv)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__s9ZOp
                  )}
                >
                  {"120+"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__ejNxS
                  )}
                >
                  {"Casinos reviewd"}
                </div>
              </div>
            </React.Fragment>
          ),

          value: args.content
        })}
      </div>
    </div>
  );
}

const PlasmicDescendants = {
  root: ["root", "wrap"],
  wrap: ["wrap"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicInfoDotPanel__ArgProps,
          internalVariantPropNames: PlasmicInfoDotPanel__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicInfoDotPanel__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicInfoDotPanel";
  } else {
    func.displayName = `PlasmicInfoDotPanel.${nodeName}`;
  }
  return func;
}

export const PlasmicInfoDotPanel = Object.assign(
  // Top-level PlasmicInfoDotPanel renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    wrap: makeNodeComponent("wrap"),
    // Metadata about props expected for PlasmicInfoDotPanel
    internalVariantProps: PlasmicInfoDotPanel__VariantProps,
    internalArgProps: PlasmicInfoDotPanel__ArgProps
  }
);

export default PlasmicInfoDotPanel;
/* prettier-ignore-end */
