/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 1LHryFzrfagz6s5XszxyaX
// Component: vGoC4GKdwTta
import * as React from "react";
import { useRouter } from "next/router";
import {
  PlasmicImg as PlasmicImg__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import LinkButton from "../../LinkButton"; // plasmic-import: IXlYPJ9laVnz/component
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 1LHryFzrfagz6s5XszxyaX/styleTokensProvider
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic.module.css"; // plasmic-import: 1LHryFzrfagz6s5XszxyaX/projectcss
import sty from "./PlasmicCardCasinoDetails.module.css"; // plasmic-import: vGoC4GKdwTta/css
import ZapIcon from "./icons/PlasmicIcon__Zap"; // plasmic-import: rZ8hz7v-qc_C/icon

createPlasmicElementProxy;

export const PlasmicCardCasinoDetails__VariantProps = new Array();

export const PlasmicCardCasinoDetails__ArgProps = new Array();

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicCardCasinoDetails__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );
  const $props = {
    ...args,
    ...variants
  };
  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const styleTokensClassNames = _useStyleTokens();
  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.root,
        "bg-grain"
      )}
    >
      <div className={classNames(projectcss.all, sty.freeBox__snhR6)} />
      <div className={classNames(projectcss.all, sty.freeBox__yOzXt)}>
        <div className={classNames(projectcss.all, sty.freeBox__ogUsS)}>
          <ZapIcon
            data-plasmic-name={"svg"}
            data-plasmic-override={overrides.svg}
            className={classNames(projectcss.all, sty.svg)}
            role={"img"}
          />
        </div>
        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text__lI2FP
          )}
        >
          {"Quick takeaway"}
        </div>
      </div>
      <div
        className={classNames(
          projectcss.all,
          projectcss.__wab_text,
          sty.text__nBuFw
        )}
      >
        {
          "The best crypto casino is usually the one with clear bonus terms, reliable withdrawals, strong game quality, and support for the coins you actually use."
        }
      </div>
      <div className={classNames(projectcss.all, sty.freeBox__xz3QP)}>
        <div className={classNames(projectcss.all, sty.freeBox__jFzkA)}>
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__pvyxC
            )}
          >
            {"Best for"}
          </div>
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text___2T5Tp
            )}
          >
            {"New and intermediate players"}
          </div>
        </div>
        <div className={classNames(projectcss.all, sty.freeBox___08Fjb)}>
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__u61F2
            )}
          >
            {"Focus"}
          </div>
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__rXzwc
            )}
          >
            {"Safety, payouts, bonus value"}
          </div>
        </div>
        <div className={classNames(projectcss.all, sty.freeBox__zvM2R)}>
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__gNgu4
            )}
          >
            {"Coins mentioned"}
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__zavCg)}>
            <PlasmicImg__
              alt={""}
              className={classNames(sty.img__n8SIh)}
              displayHeight={"auto"}
              displayMaxHeight={"none"}
              displayMaxWidth={"100%"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"20px"}
              loading={"lazy"}
              src={{
                src: "/plasmic/cryptocasinos/images/image3.png",
                fullWidth: 64,
                fullHeight: 64,
                aspectRatio: undefined
              }}
            />

            <PlasmicImg__
              alt={""}
              className={classNames(sty.img__aPSfe)}
              displayHeight={"auto"}
              displayMaxHeight={"none"}
              displayMaxWidth={"100%"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"20px"}
              loading={"lazy"}
              src={{
                src: "/plasmic/cryptocasinos/images/image4.png",
                fullWidth: 64,
                fullHeight: 64,
                aspectRatio: undefined
              }}
            />

            <PlasmicImg__
              alt={""}
              className={classNames(sty.img__ihbbf)}
              displayHeight={"auto"}
              displayMaxHeight={"none"}
              displayMaxWidth={"100%"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"20px"}
              loading={"lazy"}
              src={{
                src: "/plasmic/cryptocasinos/images/image8.png",
                fullWidth: 64,
                fullHeight: 64,
                aspectRatio: undefined
              }}
            />
          </div>
        </div>
      </div>
      <LinkButton
        data-plasmic-name={"linkButton"}
        data-plasmic-override={overrides.linkButton}
        className={classNames("__wab_instance", sty.linkButton)}
        size={"medium"}
        title={"Compare Top Casinos"}
      />
    </div>
  );
}

const PlasmicDescendants = {
  root: ["root", "svg", "linkButton"],
  svg: ["svg"],
  linkButton: ["linkButton"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicCardCasinoDetails__ArgProps,
          internalVariantPropNames: PlasmicCardCasinoDetails__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicCardCasinoDetails__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicCardCasinoDetails";
  } else {
    func.displayName = `PlasmicCardCasinoDetails.${nodeName}`;
  }
  return func;
}

export const PlasmicCardCasinoDetails = Object.assign(
  // Top-level PlasmicCardCasinoDetails renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    svg: makeNodeComponent("svg"),
    linkButton: makeNodeComponent("linkButton"),
    // Metadata about props expected for PlasmicCardCasinoDetails
    internalVariantProps: PlasmicCardCasinoDetails__VariantProps,
    internalArgProps: PlasmicCardCasinoDetails__ArgProps
  }
);

export default PlasmicCardCasinoDetails;
/* prettier-ignore-end */
