/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 1LHryFzrfagz6s5XszxyaX
// Component: uVYTGz9cJOUu
import * as React from "react";
import { useRouter } from "next/router";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 1LHryFzrfagz6s5XszxyaX/styleTokensProvider
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic.module.css"; // plasmic-import: 1LHryFzrfagz6s5XszxyaX/projectcss
import sty from "./PlasmicCornerTDivider.module.css"; // plasmic-import: uVYTGz9cJOUu/css
import CornerTSvgIcon from "./icons/PlasmicIcon__CornerTSvg"; // plasmic-import: Xd6Jep1FYsA3/icon

createPlasmicElementProxy;

export const PlasmicCornerTDivider__VariantProps = new Array();

export const PlasmicCornerTDivider__ArgProps = new Array();

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicCornerTDivider__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );
  const $props = {
    ...args,
    ...variants
  };
  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const styleTokensClassNames = _useStyleTokens();
  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.root
      )}
    >
      <CornerTSvgIcon
        className={classNames(projectcss.all, sty.svg___1HyZh)}
        role={"img"}
      />

      <CornerTSvgIcon
        className={classNames(projectcss.all, sty.svg___34Ez6)}
        role={"img"}
      />
    </div>
  );
}

const PlasmicDescendants = {
  root: ["root"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicCornerTDivider__ArgProps,
          internalVariantPropNames: PlasmicCornerTDivider__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicCornerTDivider__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicCornerTDivider";
  } else {
    func.displayName = `PlasmicCornerTDivider.${nodeName}`;
  }
  return func;
}

export const PlasmicCornerTDivider = Object.assign(
  // Top-level PlasmicCornerTDivider renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    // Metadata about props expected for PlasmicCornerTDivider
    internalVariantProps: PlasmicCornerTDivider__VariantProps,
    internalArgProps: PlasmicCornerTDivider__ArgProps
  }
);

export default PlasmicCornerTDivider;
/* prettier-ignore-end */
