/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 1LHryFzrfagz6s5XszxyaX
// Component: 20JMcDj8I9Km
import * as React from "react";
import Link from "next/link";
import { useRouter } from "next/router";
import {
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  renderPlasmicSlot
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 1LHryFzrfagz6s5XszxyaX/styleTokensProvider
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic.module.css"; // plasmic-import: 1LHryFzrfagz6s5XszxyaX/projectcss
import sty from "./PlasmicSidebarArticle.module.css"; // plasmic-import: 20JMcDj8I9Km/css

createPlasmicElementProxy;

export const PlasmicSidebarArticle__VariantProps = new Array();

export const PlasmicSidebarArticle__ArgProps = new Array(
  "cover",
  "title",
  "timeSince"
);

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicSidebarArticle__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(
    () =>
      Object.assign(
        {
          cover: {
            src: "/plasmic/cryptocasinos/images/placeholder1Jpg.jpg",
            fullWidth: 2501,
            fullHeight: 1025,
            aspectRatio: undefined
          }
        },
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );
  const $props = {
    ...args,
    ...variants
  };
  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const styleTokensClassNames = _useStyleTokens();
  return (
    <PlasmicLink__
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.a,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.root
      )}
      component={Link}
      href={`/guides/how-to-choose-a-crypto-casino`}
      legacyBehavior={false}
      platform={"nextjs"}
    >
      <PlasmicImg__
        data-plasmic-name={"img"}
        data-plasmic-override={overrides.img}
        alt={""}
        className={classNames(sty.img)}
        displayHeight={"80px"}
        displayMaxHeight={"none"}
        displayMaxWidth={"100%"}
        displayMinHeight={"0"}
        displayMinWidth={"0"}
        displayWidth={"80px"}
        loading={"lazy"}
        src={args.cover}
      />

      <div className={classNames(projectcss.all, sty.freeBox__aWqF8)}>
        <div className={classNames(projectcss.all, sty.freeBox___1DRgd)}>
          {renderPlasmicSlot({
            defaultContents: "Best mobile crypto casinos in 2026",
            value: args.title,
            className: classNames(sty.slotTargetTitle)
          })}
        </div>
        <div className={classNames(projectcss.all, sty.freeBox__xxBxG)}>
          {renderPlasmicSlot({
            defaultContents: "2 days ago",
            value: args.timeSince,
            className: classNames(sty.slotTargetTimeSince)
          })}
        </div>
      </div>
    </PlasmicLink__>
  );
}

const PlasmicDescendants = {
  root: ["root", "img"],
  img: ["img"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicSidebarArticle__ArgProps,
          internalVariantPropNames: PlasmicSidebarArticle__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicSidebarArticle__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicSidebarArticle";
  } else {
    func.displayName = `PlasmicSidebarArticle.${nodeName}`;
  }
  return func;
}

export const PlasmicSidebarArticle = Object.assign(
  // Top-level PlasmicSidebarArticle renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    img: makeNodeComponent("img"),
    // Metadata about props expected for PlasmicSidebarArticle
    internalVariantProps: PlasmicSidebarArticle__VariantProps,
    internalArgProps: PlasmicSidebarArticle__ArgProps
  }
);

export default PlasmicSidebarArticle;
/* prettier-ignore-end */
