/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 1LHryFzrfagz6s5XszxyaX
// Component: OMdPTI3XFm3i
import * as React from "react";
import { useRouter } from "next/router";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import RowChangelog from "../../RowChangelog"; // plasmic-import: iOOjtDw_sc94/component
import LinkButton from "../../LinkButton"; // plasmic-import: IXlYPJ9laVnz/component
import HandleRecentChanges from "../../HandleRecentChanges"; // plasmic-import: IQ2c8c_hDkmi/component
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 1LHryFzrfagz6s5XszxyaX/styleTokensProvider
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic.module.css"; // plasmic-import: 1LHryFzrfagz6s5XszxyaX/projectcss
import sty from "./PlasmicSectionChangelog.module.css"; // plasmic-import: OMdPTI3XFm3i/css

createPlasmicElementProxy;

export const PlasmicSectionChangelog__VariantProps = new Array();

export const PlasmicSectionChangelog__ArgProps = new Array();

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicSectionChangelog__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );
  const $props = {
    ...args,
    ...variants
  };
  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const styleTokensClassNames = _useStyleTokens();
  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.root
      )}
    >
      <div
        data-plasmic-name={"accordion"}
        data-plasmic-override={overrides.accordion}
        className={classNames(projectcss.all, sty.accordion)}
      >
        <div
          data-plasmic-name={"content"}
          data-plasmic-override={overrides.content}
          className={classNames(projectcss.all, sty.content)}
        >
          <RowChangelog
            className={classNames("__wab_instance", sty.rowChangelog__oSvGp)}
          />

          <RowChangelog
            className={classNames("__wab_instance", sty.rowChangelog__ju7Uz)}
          />

          <RowChangelog
            className={classNames("__wab_instance", sty.rowChangelog__vt7W2)}
          />

          <div
            data-plasmic-name={"freeBox"}
            data-plasmic-override={overrides.freeBox}
            className={classNames(projectcss.all, sty.freeBox)}
          >
            <LinkButton
              data-plasmic-name={"linkButton"}
              data-plasmic-override={overrides.linkButton}
              className={classNames("__wab_instance", sty.linkButton)}
              color={"gray"}
              size={"small"}
              title={"Load more"}
            />
          </div>
        </div>
      </div>
      <HandleRecentChanges
        data-plasmic-name={"handleRecentChanges"}
        data-plasmic-override={overrides.handleRecentChanges}
        className={classNames("__wab_instance", sty.handleRecentChanges)}
      />
    </div>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "accordion",
    "content",
    "freeBox",
    "linkButton",
    "handleRecentChanges"
  ],

  accordion: ["accordion", "content", "freeBox", "linkButton"],
  content: ["content", "freeBox", "linkButton"],
  freeBox: ["freeBox", "linkButton"],
  linkButton: ["linkButton"],
  handleRecentChanges: ["handleRecentChanges"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicSectionChangelog__ArgProps,
          internalVariantPropNames: PlasmicSectionChangelog__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicSectionChangelog__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicSectionChangelog";
  } else {
    func.displayName = `PlasmicSectionChangelog.${nodeName}`;
  }
  return func;
}

export const PlasmicSectionChangelog = Object.assign(
  // Top-level PlasmicSectionChangelog renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    accordion: makeNodeComponent("accordion"),
    content: makeNodeComponent("content"),
    freeBox: makeNodeComponent("freeBox"),
    linkButton: makeNodeComponent("linkButton"),
    handleRecentChanges: makeNodeComponent("handleRecentChanges"),
    // Metadata about props expected for PlasmicSectionChangelog
    internalVariantProps: PlasmicSectionChangelog__VariantProps,
    internalArgProps: PlasmicSectionChangelog__ArgProps
  }
);

export default PlasmicSectionChangelog;
/* prettier-ignore-end */
