/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 1LHryFzrfagz6s5XszxyaX
// Component: vGoC4GKdwTta
import * as React from "react";
import { useRouter } from "next/router";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  renderPlasmicSlot
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import TagPill from "../../TagPill"; // plasmic-import: nn118kQlMOAC/component
import LinkCoinIcon from "../../LinkCoinIcon"; // plasmic-import: q2l6s7HIpw7u/component
import LinkButton from "../../LinkButton"; // plasmic-import: IXlYPJ9laVnz/component
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 1LHryFzrfagz6s5XszxyaX/styleTokensProvider
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic.module.css"; // plasmic-import: 1LHryFzrfagz6s5XszxyaX/projectcss
import sty from "./PlasmicCardCasinoDetails.module.css"; // plasmic-import: vGoC4GKdwTta/css
import ZapIcon from "./icons/PlasmicIcon__Zap"; // plasmic-import: rZ8hz7v-qc_C/icon

createPlasmicElementProxy;

export const PlasmicCardCasinoDetails__VariantProps = new Array();

export const PlasmicCardCasinoDetails__ArgProps = new Array("coins");

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicCardCasinoDetails__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );
  const $props = {
    ...args,
    ...variants
  };
  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const styleTokensClassNames = _useStyleTokens();
  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.root,
        "card-grain"
      )}
    >
      <div className={classNames(projectcss.all, sty.freeBox__yOzXt)}>
        <div className={classNames(projectcss.all, sty.freeBox__ogUsS)}>
          <ZapIcon
            data-plasmic-name={"svg"}
            data-plasmic-override={overrides.svg}
            className={classNames(projectcss.all, sty.svg)}
            role={"img"}
          />
        </div>
        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text__lI2FP
          )}
        >
          {"Quick takeaway"}
        </div>
      </div>
      <div
        className={classNames(
          projectcss.all,
          projectcss.__wab_text,
          sty.text__nBuFw
        )}
      >
        {
          "The best crypto casino is usually the one with clear bonus terms, reliable withdrawals, strong game quality, and support for the coins you actually use."
        }
      </div>
      <div className={classNames(projectcss.all, sty.freeBox__xz3QP)}>
        <div className={classNames(projectcss.all, sty.freeBox__jFzkA)}>
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__pvyxC
            )}
          >
            {"Published at"}
          </div>
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text___2T5Tp
            )}
          >
            {"Mar 1, 2026"}
          </div>
        </div>
        <div className={classNames(projectcss.all, sty.freeBox__rb7PE)}>
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__xi9Vp
            )}
          >
            {"Updated at"}
          </div>
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__zHbJz
            )}
          >
            {"Mar 23, 2026"}
          </div>
        </div>
        <div className={classNames(projectcss.all, sty.freeBox__weJeq)}>
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__idpTi
            )}
          >
            {"Best for"}
          </div>
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text___6BOr0
            )}
          >
            {"New and intermediate players"}
          </div>
        </div>
        <div className={classNames(projectcss.all, sty.freeBox___08Fjb)}>
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__u61F2
            )}
          >
            {"Focus"}
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__iuERx)}>
            <TagPill
              className={classNames("__wab_instance", sty.tagPill__bAbxD)}
              title={"Safety"}
            />

            <TagPill
              className={classNames("__wab_instance", sty.tagPill__zbZ0E)}
              title={"Payouts"}
            />

            <TagPill
              className={classNames("__wab_instance", sty.tagPill__kogL3)}
              title={"Bonus value"}
            />
          </div>
        </div>
        <div className={classNames(projectcss.all, sty.freeBox__zvM2R)}>
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__gNgu4
            )}
          >
            {"Coins mentioned"}
          </div>
          <div
            className={classNames(
              projectcss.all,
              sty.freeBox__g1Tkk,
              "link-coin-icon-wrap"
            )}
          >
            {renderPlasmicSlot({
              defaultContents: (
                <React.Fragment>
                  <LinkCoinIcon
                    className={classNames(
                      "__wab_instance",
                      sty.linkCoinIcon___6Nmmy
                    )}
                    size={"small"}
                  />

                  <LinkCoinIcon
                    className={classNames(
                      "__wab_instance",
                      sty.linkCoinIcon__uRvwj
                    )}
                    icon={{
                      src: "/plasmic/cryptocasinos/images/coinEthSvg.svg",
                      fullWidth: 225,
                      fullHeight: 225,
                      aspectRatio: 1
                    }}
                    size={"small"}
                  />

                  <LinkCoinIcon
                    className={classNames(
                      "__wab_instance",
                      sty.linkCoinIcon___5I1HG
                    )}
                    icon={{
                      src: "/plasmic/cryptocasinos/images/coinSolSvg.svg",
                      fullWidth: 225,
                      fullHeight: 225,
                      aspectRatio: 1
                    }}
                    size={"small"}
                  />
                </React.Fragment>
              ),

              value: args.coins
            })}
          </div>
        </div>
      </div>
      <LinkButton
        data-plasmic-name={"linkButton"}
        data-plasmic-override={overrides.linkButton}
        className={classNames("__wab_instance", sty.linkButton)}
        href={`/casinos`}
        size={"medium"}
        title={"Compare Top Casinos"}
      />
    </div>
  );
}

const PlasmicDescendants = {
  root: ["root", "svg", "linkButton"],
  svg: ["svg"],
  linkButton: ["linkButton"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicCardCasinoDetails__ArgProps,
          internalVariantPropNames: PlasmicCardCasinoDetails__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicCardCasinoDetails__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicCardCasinoDetails";
  } else {
    func.displayName = `PlasmicCardCasinoDetails.${nodeName}`;
  }
  return func;
}

export const PlasmicCardCasinoDetails = Object.assign(
  // Top-level PlasmicCardCasinoDetails renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    svg: makeNodeComponent("svg"),
    linkButton: makeNodeComponent("linkButton"),
    // Metadata about props expected for PlasmicCardCasinoDetails
    internalVariantProps: PlasmicCardCasinoDetails__VariantProps,
    internalArgProps: PlasmicCardCasinoDetails__ArgProps
  }
);

export default PlasmicCardCasinoDetails;
/* prettier-ignore-end */
