/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 1LHryFzrfagz6s5XszxyaX
// Component: OXSVHEvZKoQP
import * as React from "react";
import Link from "next/link";
import { useRouter } from "next/router";
import {
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  hasVariant,
  renderPlasmicSlot,
  useDollarState
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 1LHryFzrfagz6s5XszxyaX/styleTokensProvider
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic.module.css"; // plasmic-import: 1LHryFzrfagz6s5XszxyaX/projectcss
import sty from "./PlasmicCoinPriceSidebarItem.module.css"; // plasmic-import: OXSVHEvZKoQP/css

createPlasmicElementProxy;

export const PlasmicCoinPriceSidebarItem__VariantProps = new Array(
  "isNegative"
);

export const PlasmicCoinPriceSidebarItem__ArgProps = new Array(
  "icon",
  "title",
  "handle",
  "price"
);

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicCoinPriceSidebarItem__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(
    () =>
      Object.assign(
        {
          icon: {
            src: "/plasmic/cryptocasinos/images/bitcoinCircleSvg.svg",
            fullWidth: 64,
            fullHeight: 64,
            aspectRatio: undefined
          }
        },
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );
  const $props = {
    ...args,
    ...variants
  };
  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const stateSpecs = React.useMemo(
    () => [
      {
        path: "isNegative",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => $props.isNegative
      }
    ],

    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $q: {},
    $refs
  });
  const styleTokensClassNames = _useStyleTokens();
  return (
    <PlasmicLink__
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.a,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.root,
        { [sty.rootisNegative]: hasVariant($state, "isNegative", "isNegative") }
      )}
      component={Link}
      href={`/coins/btc`}
      legacyBehavior={false}
      platform={"nextjs"}
    >
      <PlasmicImg__
        data-plasmic-name={"img"}
        data-plasmic-override={overrides.img}
        alt={""}
        className={classNames(sty.img)}
        displayHeight={"auto"}
        displayMaxHeight={"none"}
        displayMaxWidth={"100%"}
        displayMinHeight={"0"}
        displayMinWidth={"0"}
        displayWidth={"22px"}
        loading={"lazy"}
        src={args.icon}
      />

      <div className={classNames(projectcss.all, sty.freeBox__qg1K6)}>
        {renderPlasmicSlot({
          defaultContents: "Bitcoin",
          value: args.title,
          className: classNames(sty.slotTargetTitle)
        })}
        <div className={classNames(projectcss.all, sty.freeBox__lktys)}>
          {renderPlasmicSlot({
            defaultContents: "BTC",
            value: args.handle,
            className: classNames(sty.slotTargetHandle)
          })}
        </div>
      </div>
      <div className={classNames(projectcss.all, sty.freeBox__tuYgq)}>
        {renderPlasmicSlot({
          defaultContents: "$64,230",
          value: args.price,
          className: classNames(sty.slotTargetPrice)
        })}
        <div
          data-plasmic-name={"change"}
          data-plasmic-override={overrides.change}
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.change,
            {
              [sty.changeisNegative]: hasVariant(
                $state,
                "isNegative",
                "isNegative"
              )
            }
          )}
        >
          {"+2,4%"}
        </div>
      </div>
    </PlasmicLink__>
  );
}

const PlasmicDescendants = {
  root: ["root", "img", "change"],
  img: ["img"],
  change: ["change"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicCoinPriceSidebarItem__ArgProps,
          internalVariantPropNames: PlasmicCoinPriceSidebarItem__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicCoinPriceSidebarItem__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicCoinPriceSidebarItem";
  } else {
    func.displayName = `PlasmicCoinPriceSidebarItem.${nodeName}`;
  }
  return func;
}

export const PlasmicCoinPriceSidebarItem = Object.assign(
  // Top-level PlasmicCoinPriceSidebarItem renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    img: makeNodeComponent("img"),
    change: makeNodeComponent("change"),
    // Metadata about props expected for PlasmicCoinPriceSidebarItem
    internalVariantProps: PlasmicCoinPriceSidebarItem__VariantProps,
    internalArgProps: PlasmicCoinPriceSidebarItem__ArgProps
  }
);

export default PlasmicCoinPriceSidebarItem;
/* prettier-ignore-end */
