/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 1LHryFzrfagz6s5XszxyaX
// Component: 9i_F_lMez6u7
import * as React from "react";
import Head from "next/head";
import { useRouter } from "next/router";
import {
  PlasmicImg as PlasmicImg__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import CoinPriceMarquee from "../../CoinPriceMarquee"; // plasmic-import: tGnuTHE96HBi/component
import HeroCardLink from "../../HeroCardLink"; // plasmic-import: QXwWWXLv7dKm/component
import CornerTDivider from "../../CornerTDivider"; // plasmic-import: uVYTGz9cJOUu/component
import LinkButton from "../../LinkButton"; // plasmic-import: IXlYPJ9laVnz/component
import CardCasinoList from "../../CardCasinoList"; // plasmic-import: 6YxcbeY1AF1_/component
import CardBentoTopic from "../../CardBentoTopic"; // plasmic-import: U8ruvn_mupQO/component
import CardPriceChart from "../../CardPriceChart"; // plasmic-import: Bygnfqie3Cqa/component
import LinkSidebar from "../../LinkSidebar"; // plasmic-import: 9cwbKxCRtECB/component
import CoinPriceSidebarItem from "../../CoinPriceSidebarItem"; // plasmic-import: OXSVHEvZKoQP/component
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 1LHryFzrfagz6s5XszxyaX/styleTokensProvider
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic.module.css"; // plasmic-import: 1LHryFzrfagz6s5XszxyaX/projectcss
import sty from "./PlasmicHomepage.module.css"; // plasmic-import: 9i_F_lMez6u7/css
import ShieldCheckIcon from "./icons/PlasmicIcon__ShieldCheck"; // plasmic-import: B8aXAFRTKbUL/icon
import TrophyIcon from "./icons/PlasmicIcon__Trophy"; // plasmic-import: I-1KWj6kHo73/icon
import GiftIcon from "./icons/PlasmicIcon__Gift"; // plasmic-import: JLJyojIPy5bM/icon
import ChartLineIcon from "./icons/PlasmicIcon__ChartLine"; // plasmic-import: cBRHEkj-bEJ3/icon
import BookIcon from "./icons/PlasmicIcon__Book"; // plasmic-import: h9sLGs5m_Vd1/icon
import BadgeCheckIcon from "./icons/PlasmicIcon__BadgeCheck"; // plasmic-import: OE1F_elgA17S/icon
import ShieldOffIcon from "./icons/PlasmicIcon__ShieldOff"; // plasmic-import: LGewn1q6HySZ/icon
import MoneyArrowDownIcon from "./icons/PlasmicIcon__MoneyArrowDown"; // plasmic-import: LxA7vPyY9CLd/icon
import DiceIcon from "./icons/PlasmicIcon__Dice"; // plasmic-import: uZVnQmbmAoUm/icon
import CrownIcon from "./icons/PlasmicIcon__Crown"; // plasmic-import: BBZInROpO67i/icon
import CoinsIcon from "./icons/PlasmicIcon__Coins"; // plasmic-import: YH9P_qiC8MJ-/icon
import HandshakeIcon from "./icons/PlasmicIcon__Handshake"; // plasmic-import: 5yXXrMkLRYRW/icon
import LockIcon from "./icons/PlasmicIcon__Lock"; // plasmic-import: TcA6uFpu7JRC/icon
import ListSearchIcon from "./icons/PlasmicIcon__ListSearch"; // plasmic-import: Y_uxftxiiUAz/icon
import ZapIcon from "./icons/PlasmicIcon__Zap"; // plasmic-import: rZ8hz7v-qc_C/icon
import StarIcon from "./icons/PlasmicIcon__Star"; // plasmic-import: KIRkdu8buNhp/icon
import ListCheckIcon from "./icons/PlasmicIcon__ListCheck"; // plasmic-import: w5YHMvzaEKho/icon

const emptyProxy = new Proxy(() => "", {
  get(_, prop) {
    return prop === Symbol.toPrimitive ? () => "" : emptyProxy;
  }
});

function wrapQueriesWithLoadingProxy($q) {
  return new Proxy($q, {
    get(target, queryName) {
      const query = target[queryName];
      return !query || query.isLoading || !query.data ? emptyProxy : query;
    }
  });
}

export function generateDynamicMetadata($q, $ctx) {
  return {
    openGraph: {},
    twitter: {
      card: "summary"
    }
  };
}

createPlasmicElementProxy;

export const PlasmicHomepage__VariantProps = new Array();

export const PlasmicHomepage__ArgProps = new Array();

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicHomepage__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );
  const $props = {
    ...args,
    ...variants
  };
  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const pageMetadata = generateDynamicMetadata(
    wrapQueriesWithLoadingProxy({}),
    $ctx
  );
  const styleTokensClassNames = _useStyleTokens();
  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            styleTokensClassNames,
            sty.root
          )}
        >
          <CoinPriceMarquee
            data-plasmic-name={"coinPriceMarquee"}
            data-plasmic-override={overrides.coinPriceMarquee}
            className={classNames("__wab_instance", sty.coinPriceMarquee)}
          />

          <div
            data-plasmic-name={"hero"}
            data-plasmic-override={overrides.hero}
            className={classNames(projectcss.all, sty.hero)}
          >
            <div className={classNames(projectcss.all, sty.freeBox__uwDL)}>
              <div className={classNames(projectcss.all, sty.freeBox__su1M)}>
                <ShieldCheckIcon
                  className={classNames(projectcss.all, sty.svg__xYsu)}
                  role={"img"}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__bYrX
                  )}
                >
                  {
                    "Trusted rankings, live prices and expert crypto casino guides"
                  }
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.freeBox___5EE1J)}>
                <div className={classNames(projectcss.all, sty.freeBox__hAhg2)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__zfd0H
                    )}
                  >
                    {"Crypto Casinos"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__yBqNe
                    )}
                  >
                    <React.Fragment>
                      <React.Fragment>{"Find "}</React.Fragment>
                      {
                        <span
                          data-plasmic-name={"span"}
                          data-plasmic-override={overrides.span}
                          className={classNames(
                            projectcss.all,
                            projectcss.span,
                            projectcss.__wab_text,
                            projectcss.plasmic_default__inline,
                            sty.span
                          )}
                        >
                          {"the best"}
                        </span>
                      }
                      <React.Fragment>
                        {" crypto casinos, bonuses and guides."}
                      </React.Fragment>
                    </React.Fragment>
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___6ZUtg
                    )}
                  >
                    {
                      "Navigate the expanding world of blockchain casinos with confidence. We verify fairness, audit bonuses, and track the fastest withdrawals."
                    }
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__zyhl8)}>
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__nnm7V)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"50%"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/cryptocasinos/images/ccIcon.svg",
                      fullWidth: 136.76,
                      fullHeight: 136.76,
                      aspectRatio: 1
                    }}
                  />

                  <div
                    className={classNames(projectcss.all, sty.freeBox__vDed5)}
                  />
                </div>
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  sty.freeBox__qWeFb,
                  "bg-grain"
                )}
              >
                <div
                  className={classNames(projectcss.all, sty.freeBox__roAk)}
                />

                <HeroCardLink
                  className={classNames(
                    "__wab_instance",
                    sty.heroCardLink__sQrQc
                  )}
                  icon={
                    <TrophyIcon
                      className={classNames(projectcss.all, sty.svg__va2ZQ)}
                      role={"img"}
                    />
                  }
                />

                <CornerTDivider
                  className={classNames(
                    "__wab_instance",
                    sty.cornerTDivider___3FMoy
                  )}
                />

                <HeroCardLink
                  className={classNames(
                    "__wab_instance",
                    sty.heroCardLink___07JSb
                  )}
                  description={
                    "See no-deposit deals, free spins, and match bonuses with less noise."
                  }
                  icon={
                    <GiftIcon
                      className={classNames(projectcss.all, sty.svg__gyMsn)}
                      role={"img"}
                    />
                  }
                  title={"Bonus comparisons"}
                />

                <CornerTDivider
                  className={classNames(
                    "__wab_instance",
                    sty.cornerTDivider__tJa0M
                  )}
                />

                <HeroCardLink
                  className={classNames(
                    "__wab_instance",
                    sty.heroCardLink__llku
                  )}
                  description={
                    "Track BTC, ETH, SOL, and other coins players use most for deposits."
                  }
                  icon={
                    <ChartLineIcon
                      className={classNames(projectcss.all, sty.svg__qppq)}
                      role={"img"}
                    />
                  }
                  title={"Live crypto prices"}
                />

                <CornerTDivider
                  className={classNames(
                    "__wab_instance",
                    sty.cornerTDivider__e9Fx0
                  )}
                />

                <HeroCardLink
                  className={classNames(
                    "__wab_instance",
                    sty.heroCardLink__uBcEg
                  )}
                  description={
                    "Learn no-KYC, provably fair, wallet setup, and safer ways to compare sites."
                  }
                  icon={
                    <BookIcon
                      className={classNames(projectcss.all, sty.svg___0LuN0)}
                      role={"img"}
                    />
                  }
                  title={"Expert guides"}
                />
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__wse2R)}>
                <div className={classNames(projectcss.all, sty.freeBox__hQlk)}>
                  <LinkButton
                    className={classNames(
                      "__wab_instance",
                      sty.linkButton___3DaL
                    )}
                  />

                  <LinkButton
                    className={classNames(
                      "__wab_instance",
                      sty.linkButton__db89C
                    )}
                    color={"gray"}
                    title={"Browse Guides"}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__hmk3I)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__wkW16
                    )}
                  >
                    {"Explore Coins"}
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox___1OOz)}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__te50K)}
                      displayHeight={"30px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"30px"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/cryptocasinos/images/bitcoinCircleSvg.svg",
                        fullWidth: 64,
                        fullHeight: 64,
                        aspectRatio: undefined
                      }}
                    />

                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__uvZmG)}
                      displayHeight={"30px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"30px"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/cryptocasinos/images/bitcoinCircleSvg.svg",
                        fullWidth: 64,
                        fullHeight: 64,
                        aspectRatio: undefined
                      }}
                    />

                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__usdHh)}
                      displayHeight={"30px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"30px"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/cryptocasinos/images/bitcoinCircleSvg.svg",
                        fullWidth: 64,
                        fullHeight: 64,
                        aspectRatio: undefined
                      }}
                    />

                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__ssJCz)}
                      displayHeight={"30px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"30px"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/cryptocasinos/images/bitcoinCircleSvg.svg",
                        fullWidth: 64,
                        fullHeight: 64,
                        aspectRatio: undefined
                      }}
                    />

                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__q30HL)}
                      displayHeight={"30px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"30px"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/cryptocasinos/images/bitcoinCircleSvg.svg",
                        fullWidth: 64,
                        fullHeight: 64,
                        aspectRatio: undefined
                      }}
                    />
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__ezV7R)} />
          <div
            data-plasmic-name={"content"}
            data-plasmic-override={overrides.content}
            className={classNames(projectcss.all, sty.content)}
          >
            <div className={classNames(projectcss.all, sty.freeBox__im7X0)}>
              <div className={classNames(projectcss.all, sty.freeBox__flQ7X)}>
                <div className={classNames(projectcss.all, sty.freeBox__gwa5)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__gUSz0
                    )}
                  >
                    {"Recommended Crypto Casinos"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__vLjsy
                    )}
                  >
                    {
                      "The currently most recommended crypto casinos based on our expert reviews."
                    }
                  </div>
                </div>
                <LinkButton
                  className={classNames(
                    "__wab_instance",
                    sty.linkButton__rx2PR
                  )}
                  color={"gray"}
                  title={"Compare  all"}
                />
              </div>
              <div
                data-plasmic-name={"cardsCasinos"}
                data-plasmic-override={overrides.cardsCasinos}
                className={classNames(projectcss.all, sty.cardsCasinos)}
              >
                <CardCasinoList
                  className={classNames(
                    "__wab_instance",
                    sty.cardCasinoList___16GSh
                  )}
                />

                <CardCasinoList
                  className={classNames(
                    "__wab_instance",
                    sty.cardCasinoList__dbTnp
                  )}
                  logo={{
                    src: "/plasmic/cryptocasinos/images/roobetLogoSvg.svg",
                    fullWidth: 516.85,
                    fullHeight: 517,
                    aspectRatio: 0.99971
                  }}
                  position={"#2"}
                  title={"Roobet"}
                />

                <CardCasinoList
                  className={classNames(
                    "__wab_instance",
                    sty.cardCasinoList__owWlM
                  )}
                  logo={{
                    src: "/plasmic/cryptocasinos/images/wildioLogoSvg.svg",
                    fullWidth: 163,
                    fullHeight: 204,
                    aspectRatio: 0.79902
                  }}
                  position={"#3"}
                  title={"Wild.io"}
                />
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__mdNnw)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__nluua
                  )}
                >
                  {
                    "We rank casinos by reputation, bonus clarity, withdrawal speed, and supported payment methods."
                  }
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__da6)}>
                  <BadgeCheckIcon
                    className={classNames(projectcss.all, sty.svg__uHgOf)}
                    role={"img"}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__byZxI
                    )}
                  >
                    {"How we rank casinos"}
                  </div>
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__skRui)}>
                <div className={classNames(projectcss.all, sty.freeBox__e0AI3)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__usQ
                    )}
                  >
                    {"Explore Casino Topics"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__kPqEo
                    )}
                  >
                    {
                      "Explore crypto casino categories like No-KYC, Non-sticky, Fast payouts and other popular topics."
                    }
                  </div>
                </div>
                <LinkButton
                  className={classNames(
                    "__wab_instance",
                    sty.linkButton__aNehe
                  )}
                  color={"gray"}
                  title={"Browse Topics"}
                />
              </div>
              <div className={classNames(projectcss.all, sty.freeBox___6UUYu)}>
                <CardBentoTopic
                  className={classNames(
                    "__wab_instance",
                    sty.cardBentoTopic__v7Ki8
                  )}
                  icon={
                    <ShieldOffIcon
                      className={classNames(projectcss.all, sty.svg__hx3Il)}
                      role={"img"}
                    />
                  }
                  tags={
                    <React.Fragment>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__ciUfc
                        )}
                      >
                        {"Wager-free"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__kcS3T
                        )}
                      >
                        {"BTC"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__rWWgc
                        )}
                      >
                        {"Non sticky"}
                      </div>
                    </React.Fragment>
                  }
                />

                <CardBentoTopic
                  className={classNames(
                    "__wab_instance",
                    sty.cardBentoTopic__srcSr
                  )}
                  countTitle={"12 Reviews"}
                  decription={
                    "Compare approval windows, withdrawal times, and practical cashout limits."
                  }
                  icon={
                    <MoneyArrowDownIcon
                      className={classNames(projectcss.all, sty.svg__z6EAp)}
                      role={"img"}
                    />
                  }
                  tags={
                    <React.Fragment>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__h2Cj5
                        )}
                      >
                        {"Under 1 Hour"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__gDy5B
                        )}
                      >
                        {"Low fees"}
                      </div>
                    </React.Fragment>
                  }
                  title={"Fast Payouts"}
                />

                <CardBentoTopic
                  className={classNames(
                    "__wab_instance",
                    sty.cardBentoTopic___0JVp
                  )}
                  countTitle={"9 Casinos"}
                  decription={
                    "Crash, dice, limbo, and other in-house games with provably fair checks.\n"
                  }
                  icon={
                    <DiceIcon
                      className={classNames(projectcss.all, sty.svg__zqoCb)}
                      role={"img"}
                    />
                  }
                  tags={
                    <React.Fragment>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__aL3Ux
                        )}
                      >
                        {"Crash"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__qfO5O
                        )}
                      >
                        {"Dice"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__wtPLo
                        )}
                      >
                        {"Limbo"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__kcSe
                        )}
                      >
                        {"Originals"}
                      </div>
                    </React.Fragment>
                  }
                  title={"Original Games"}
                />

                <CardBentoTopic
                  className={classNames(
                    "__wab_instance",
                    sty.cardBentoTopic__ezGS
                  )}
                  countTitle={"7 guides"}
                  decription={
                    "Editors track cashback, host support, high limits, and premium reward structures."
                  }
                  icon={
                    <CrownIcon
                      className={classNames(projectcss.all, sty.svg__riu0)}
                      role={"img"}
                    />
                  }
                  tags={
                    <React.Fragment>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__cBClA
                        )}
                      >
                        {"Cashback"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__lKzcQ
                        )}
                      >
                        {"VIP Host"}
                      </div>
                    </React.Fragment>
                  }
                  title={"VIP & High Rollers"}
                />

                <CardBentoTopic
                  className={classNames(
                    "__wab_instance",
                    sty.cardBentoTopic__sz5Ib
                  )}
                  countTitle={"40+ Supported Coins"}
                  decription={
                    "Find sites that support SOL, XRP, DOGE, LTC, and broader token menus beyond BTC and ETH."
                  }
                  icon={
                    <CoinsIcon
                      className={classNames(projectcss.all, sty.svg__uLgbm)}
                      role={"img"}
                    />
                  }
                  tags={
                    <React.Fragment>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___5Qf2A
                        )}
                      >
                        {"SOL"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___7SAu
                        )}
                      >
                        {"XRP"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___0PNzt
                        )}
                      >
                        {"DOGE"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__ouZ07
                        )}
                      >
                        {"LTC"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__l1LEc
                        )}
                      >
                        {"USDT"}
                      </div>
                    </React.Fragment>
                  }
                  title={"Altcoin Firiendly Casinos"}
                />

                <CardBentoTopic
                  className={classNames(
                    "__wab_instance",
                    sty.cardBentoTopic__nHnFo
                  )}
                  countTitle={"12 Explainers"}
                  decription={
                    "Understand seeds, verification flows, and what to check before trusting results."
                  }
                  icon={
                    <HandshakeIcon
                      className={classNames(projectcss.all, sty.svg__j5YGe)}
                      role={"img"}
                    />
                  }
                  tags={
                    <React.Fragment>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__lem2S
                        )}
                      >
                        {"Verification"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__legRd
                        )}
                      >
                        {"Seeds"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__s0Y8Q
                        )}
                      >
                        {"RTP"}
                      </div>
                    </React.Fragment>
                  }
                  title={"Provably Fair Games"}
                />

                <CardBentoTopic
                  className={classNames(
                    "__wab_instance",
                    sty.cardBentoTopic__o8YrK
                  )}
                  countTitle={"6 Guides"}
                  decription={
                    "Filter deposit matches, cashback, free spins, and rollover-friendly offers."
                  }
                  icon={
                    <GiftIcon
                      className={classNames(projectcss.all, sty.svg__cB77G)}
                      role={"img"}
                    />
                  }
                  tags={
                    <React.Fragment>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__tVvC5
                        )}
                      >
                        {"Match bonus"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__oRkFg
                        )}
                      >
                        {"Free spins"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__qespK
                        )}
                      >
                        {"Bonus buy"}
                      </div>
                    </React.Fragment>
                  }
                  title={"Bonus Strategy"}
                />
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__jfhzS)}>
                <div className={classNames(projectcss.all, sty.freeBox__mkMmm)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__gOeZe
                    )}
                  >
                    {"Live Price"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__gcvB
                    )}
                  >
                    {
                      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent tempus dolor et odio hendrerit dignissim."
                    }
                  </div>
                </div>
              </div>
              <CardPriceChart
                data-plasmic-name={"cardPriceChart"}
                data-plasmic-override={overrides.cardPriceChart}
                className={classNames("__wab_instance", sty.cardPriceChart)}
              />

              <div className={classNames(projectcss.all, sty.freeBox__mhLDy)}>
                <div
                  className={classNames(projectcss.all, sty.freeBox___8G0Oa)}
                >
                  <div
                    className={classNames(projectcss.all, sty.freeBox__npRit)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__jcBbT
                      )}
                    >
                      {"Featured Articles"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__fxsEn
                      )}
                    >
                      {
                        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent tempus dolor et odio hendrerit dignissim."
                      }
                    </div>
                  </div>
                  <LinkButton
                    className={classNames(
                      "__wab_instance",
                      sty.linkButton__xSxYh
                    )}
                    color={"gray"}
                    title={"All Articles"}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.freeBox___1TBG)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      sty.freeBox__fy79P,
                      "bg-grain"
                    )}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__kxbBi)}
                    />

                    <div
                      className={classNames(projectcss.all, sty.freeBox__u4Em)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__rpryz
                        )}
                      >
                        <BookIcon
                          className={classNames(projectcss.all, sty.svg__rHDuS)}
                          role={"img"}
                        />
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__ybQbi
                        )}
                      >
                        {"Editors Pick"}
                      </div>
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__hsidx
                      )}
                    >
                      {
                        "How to choose a crypto casino: security, bonus value, and withdrawal speed"
                      }
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__k162K
                      )}
                    >
                      {
                        "This guide breaks down the signals that matter most when comparing a Bitcoin casino in 2025, including game fairness, on-chain efficiency, bonus restrictions, and country access."
                      }
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__fIoWb)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__rkLim
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__emq5N
                          )}
                        >
                          <LockIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__mcwCb
                            )}
                            role={"img"}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__y5Piu
                            )}
                          >
                            {"Security first"}
                          </div>
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__w7Cho
                          )}
                        >
                          {"Review wallet safety practices and track record."}
                        </div>
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__shAir
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__n3N97
                          )}
                        >
                          <ListSearchIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg___9DjZx
                            )}
                            role={"img"}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__asOb2
                            )}
                          >
                            {"Bonus terms"}
                          </div>
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__yqMqs
                          )}
                        >
                          {
                            "Look at rollover, max cashout, and excluded titles."
                          }
                        </div>
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__uf8Nd
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__crq67
                          )}
                        >
                          <CoinsIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg___2TlCe
                            )}
                            role={"img"}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text___9Ketc
                            )}
                          >
                            {"Coin support"}
                          </div>
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__tXhfZ
                          )}
                        >
                          {"Compare BTC, ETH, SOL, and stablecoin options."}
                        </div>
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__obox
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__mTt9B
                          )}
                        >
                          <ZapIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__lgy1O
                            )}
                            role={"img"}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__l0Vcu
                            )}
                          >
                            {"Cashout speed"}
                          </div>
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__n1VUx
                          )}
                        >
                          {"Spotlight on quick processing and clear limits."}
                        </div>
                      </div>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__oRmHi)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__qiFhH
                        )}
                      >
                        {"Read Full Guide"}
                      </div>
                    </div>
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      sty.freeBox___7081E,
                      "bg-grain"
                    )}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__xyCuI)}
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__iugxd
                      )}
                    >
                      {"News"}
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__uoXZk)}
                    >
                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img__mU22Q)}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"20px"}
                        loading={"lazy"}
                        src={{
                          src: "/plasmic/cryptocasinos/images/image3.png",
                          fullWidth: 64,
                          fullHeight: 64,
                          aspectRatio: undefined
                        }}
                      />

                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img__ucY8T)}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"20px"}
                        loading={"lazy"}
                        src={{
                          src: "/plasmic/cryptocasinos/images/image7.png",
                          fullWidth: 64,
                          fullHeight: 64,
                          aspectRatio: undefined
                        }}
                      />
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__kzpMw
                      )}
                    >
                      {
                        "How to choose a crypto casino: security, bonus value, and withdrawal speed"
                      }
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__tqznB
                      )}
                    >
                      {
                        "Operators are adjusting deposit brackets and reworking VIP retention offers."
                      }
                    </div>
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      sty.freeBox__gFdMm,
                      "bg-grain"
                    )}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__s9Af)}
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__vH7Fa
                      )}
                    >
                      {"News"}
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__hWtyx)}
                    >
                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img___2G2WZ)}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"20px"}
                        loading={"lazy"}
                        src={{
                          src: "/plasmic/cryptocasinos/images/image3.png",
                          fullWidth: 64,
                          fullHeight: 64,
                          aspectRatio: undefined
                        }}
                      />

                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img__iPg4V)}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"20px"}
                        loading={"lazy"}
                        src={{
                          src: "/plasmic/cryptocasinos/images/image4.png",
                          fullWidth: 64,
                          fullHeight: 64,
                          aspectRatio: undefined
                        }}
                      />

                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img__tD7Ol)}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"20px"}
                        loading={"lazy"}
                        src={{
                          src: "/plasmic/cryptocasinos/images/image8.png",
                          fullWidth: 64,
                          fullHeight: 64,
                          aspectRatio: undefined
                        }}
                      />
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___7YAkd
                      )}
                    >
                      {"Are stablecoins becoming the preferred payment rail?"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__eYvNp
                      )}
                    >
                      {
                        "USDT and USDC continue gaining share among readers seeking lower volatility."
                      }
                    </div>
                  </div>
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__ytNwg)}>
                <div
                  className={classNames(projectcss.all, sty.freeBox___0Mc7R)}
                >
                  <div
                    className={classNames(projectcss.all, sty.freeBox__gWmA1)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__qj7Dw
                      )}
                    >
                      {"Guides & News"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__djgq
                      )}
                    >
                      {
                        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent tempus dolor et odio hendrerit dignissim."
                      }
                    </div>
                  </div>
                  <LinkButton
                    className={classNames(
                      "__wab_instance",
                      sty.linkButton__oQsT8
                    )}
                    color={"gray"}
                    title={"Browse News"}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__uuOeC)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__qRnwK)}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__cTcZ3)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/cryptocasinos/images/placeholder1Jpg.jpg",
                        fullWidth: 2501,
                        fullHeight: 1025,
                        aspectRatio: undefined
                      }}
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        sty.freeBox___7IEp,
                        "bg-grain"
                      )}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__wwhyz
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__wPij
                          )}
                        >
                          {"News"}
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__qCyQ
                          )}
                        >
                          <PlasmicImg__
                            alt={""}
                            className={classNames(sty.img___8HbZy)}
                            displayHeight={"auto"}
                            displayMaxHeight={"none"}
                            displayMaxWidth={"100%"}
                            displayMinHeight={"0"}
                            displayMinWidth={"0"}
                            displayWidth={"20px"}
                            loading={"lazy"}
                            src={{
                              src: "/plasmic/cryptocasinos/images/image3.png",
                              fullWidth: 64,
                              fullHeight: 64,
                              aspectRatio: undefined
                            }}
                          />

                          <PlasmicImg__
                            alt={""}
                            className={classNames(sty.img__mikd)}
                            displayHeight={"auto"}
                            displayMaxHeight={"none"}
                            displayMaxWidth={"100%"}
                            displayMinHeight={"0"}
                            displayMinWidth={"0"}
                            displayWidth={"20px"}
                            loading={"lazy"}
                            src={{
                              src: "/plasmic/cryptocasinos/images/image4.png",
                              fullWidth: 64,
                              fullHeight: 64,
                              aspectRatio: undefined
                            }}
                          />

                          <PlasmicImg__
                            alt={""}
                            className={classNames(sty.img___7VlfJ)}
                            displayHeight={"auto"}
                            displayMaxHeight={"none"}
                            displayMaxWidth={"100%"}
                            displayMinHeight={"0"}
                            displayMinWidth={"0"}
                            displayWidth={"20px"}
                            loading={"lazy"}
                            src={{
                              src: "/plasmic/cryptocasinos/images/image8.png",
                              fullWidth: 64,
                              fullHeight: 64,
                              aspectRatio: undefined
                            }}
                          />
                        </div>
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___1D0Wz
                        )}
                      >
                        {"How to ensure provably fair gaming at crypto casinos"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__iQ5Oh
                        )}
                      >
                        {
                          "Learn how seed hashes, server seeds, and verification steps work so you can audit outcomes and understand what provably fair actually means."
                        }
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__tty9S
                        )}
                      >
                        {"Mar 16, 2026"}
                      </div>
                    </div>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox___7DyuS)}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__ceOfx)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/cryptocasinos/images/placeholder3Jpg.jpg",
                        fullWidth: 900,
                        fullHeight: 500,
                        aspectRatio: undefined
                      }}
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        sty.freeBox__jgm8V,
                        "bg-grain"
                      )}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__zm8Dw
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___3Uopy
                          )}
                        >
                          {"News"}
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__lqURq
                          )}
                        >
                          <PlasmicImg__
                            alt={""}
                            className={classNames(sty.img__m2Gf)}
                            displayHeight={"auto"}
                            displayMaxHeight={"none"}
                            displayMaxWidth={"100%"}
                            displayMinHeight={"0"}
                            displayMinWidth={"0"}
                            displayWidth={"20px"}
                            loading={"lazy"}
                            src={{
                              src: "/plasmic/cryptocasinos/images/image3.png",
                              fullWidth: 64,
                              fullHeight: 64,
                              aspectRatio: undefined
                            }}
                          />

                          <PlasmicImg__
                            alt={""}
                            className={classNames(sty.img___5UeKg)}
                            displayHeight={"auto"}
                            displayMaxHeight={"none"}
                            displayMaxWidth={"100%"}
                            displayMinHeight={"0"}
                            displayMinWidth={"0"}
                            displayWidth={"20px"}
                            loading={"lazy"}
                            src={{
                              src: "/plasmic/cryptocasinos/images/image4.png",
                              fullWidth: 64,
                              fullHeight: 64,
                              aspectRatio: undefined
                            }}
                          />
                        </div>
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___9Y8U2
                        )}
                      >
                        {"Bitcoin hits new highs: impact on gambling limits"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__hi59Y
                        )}
                      >
                        {
                          "Learn how seed hashes, server seeds, and verification steps work so you can audit outcomes and understand what provably fair actually means."
                        }
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__ecWjh
                        )}
                      >
                        {"Mar 16, 2026"}
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.freeBox___25Gl)}>
                <div className={classNames(projectcss.all, sty.freeBox__ehzhW)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__xVLyb)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___0Trx0
                      )}
                    >
                      {"Popular Guides"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___6Bgo2
                      )}
                    >
                      {
                        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent tempus dolor et odio hendrerit dignissim."
                      }
                    </div>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__ilcL0)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__xpEq
                      )}
                    >
                      {"All Guides"}
                    </div>
                  </div>
                </div>
                <div
                  className={classNames(projectcss.all, sty.freeBox___1OovW)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      sty.freeBox___7FlSy,
                      "bg-grain"
                    )}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__ybB8)}
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___7W7Dl
                      )}
                    >
                      {"Guide"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__ylcAi
                      )}
                    >
                      {
                        "How to choose a crypto casino: security, bonus value, and withdrawal speed"
                      }
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___6OtZy
                      )}
                    >
                      {
                        "Operators are adjusting deposit brackets and reworking VIP retention offers."
                      }
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__mfwc7)}
                    >
                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img__qbMXq)}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"20px"}
                        loading={"lazy"}
                        src={{
                          src: "/plasmic/cryptocasinos/images/image5.png",
                          fullWidth: 64,
                          fullHeight: 64,
                          aspectRatio: undefined
                        }}
                      />

                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img___9UNtg)}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"20px"}
                        loading={"lazy"}
                        src={{
                          src: "/plasmic/cryptocasinos/images/image7.png",
                          fullWidth: 64,
                          fullHeight: 64,
                          aspectRatio: undefined
                        }}
                      />

                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img__eNxJs)}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"20px"}
                        loading={"lazy"}
                        src={{
                          src: "/plasmic/cryptocasinos/images/image4.png",
                          fullWidth: 64,
                          fullHeight: 64,
                          aspectRatio: undefined
                        }}
                      />
                    </div>
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      sty.freeBox__xmBwK,
                      "bg-grain"
                    )}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__kfUMv)}
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__hRdhk
                      )}
                    >
                      {"Guide"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___5KiAc
                      )}
                    >
                      {
                        "How to choose a crypto casino: security, bonus value, and withdrawal speed"
                      }
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__paWik
                      )}
                    >
                      {
                        "Operators are adjusting deposit brackets and reworking VIP retention offers."
                      }
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__ilyl6)}
                    >
                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img__y8TJ2)}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"20px"}
                        loading={"lazy"}
                        src={{
                          src: "/plasmic/cryptocasinos/images/image3.png",
                          fullWidth: 64,
                          fullHeight: 64,
                          aspectRatio: undefined
                        }}
                      />

                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img__f8V18)}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"20px"}
                        loading={"lazy"}
                        src={{
                          src: "/plasmic/cryptocasinos/images/image8.png",
                          fullWidth: 64,
                          fullHeight: 64,
                          aspectRatio: undefined
                        }}
                      />
                    </div>
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      sty.freeBox__h4IdC,
                      "bg-grain"
                    )}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__untg)}
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__vj7Lf
                      )}
                    >
                      {"Guide"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__ddcvA
                      )}
                    >
                      {
                        "How to choose a crypto casino: security, bonus value, and withdrawal speed"
                      }
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__oUcDc
                      )}
                    >
                      {
                        "Operators are adjusting deposit brackets and reworking VIP retention offers."
                      }
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__jxOeS)}
                    >
                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img___9GdPj)}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"20px"}
                        loading={"lazy"}
                        src={{
                          src: "/plasmic/cryptocasinos/images/image3.png",
                          fullWidth: 64,
                          fullHeight: 64,
                          aspectRatio: undefined
                        }}
                      />

                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img__hncmP)}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"20px"}
                        loading={"lazy"}
                        src={{
                          src: "/plasmic/cryptocasinos/images/image4.png",
                          fullWidth: 64,
                          fullHeight: 64,
                          aspectRatio: undefined
                        }}
                      />
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div
              data-plasmic-name={"sidebar"}
              data-plasmic-override={overrides.sidebar}
              className={classNames(projectcss.all, sty.sidebar)}
            >
              <div className={classNames(projectcss.all, sty.freeBox__dbSj)}>
                <div className={classNames(projectcss.all, sty.freeBox__kPary)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__pKjnM
                    )}
                  >
                    {"Selected Categories"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__zqQwz
                    )}
                  >
                    {"See all"}
                  </div>
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    sty.freeBox__z58KV,
                    "bg-grain"
                  )}
                >
                  <LinkSidebar
                    className={classNames(
                      "__wab_instance",
                      sty.linkSidebar__rxoYu
                    )}
                    icon={
                      <StarIcon
                        className={classNames(projectcss.all, sty.svg__eYws)}
                        role={"img"}
                      />
                    }
                  />

                  <LinkSidebar
                    className={classNames(
                      "__wab_instance",
                      sty.linkSidebar__gbtVz
                    )}
                    icon={
                      <BookIcon
                        className={classNames(projectcss.all, sty.svg__nYgHq)}
                        role={"img"}
                      />
                    }
                    title={"Game Guides"}
                  />

                  <LinkSidebar
                    className={classNames(
                      "__wab_instance",
                      sty.linkSidebar___3VWCm
                    )}
                    icon={
                      <GiftIcon
                        className={classNames(projectcss.all, sty.svg__xdXt8)}
                        role={"img"}
                      />
                    }
                    title={"Bonus Codes"}
                  />

                  <LinkSidebar
                    className={classNames(
                      "__wab_instance",
                      sty.linkSidebar__mtVcx
                    )}
                    title={"Crypto News"}
                  />

                  <LinkSidebar
                    className={classNames(
                      "__wab_instance",
                      sty.linkSidebar__oId6C
                    )}
                    icon={
                      <ListCheckIcon
                        className={classNames(projectcss.all, sty.svg__kqtXw)}
                        role={"img"}
                      />
                    }
                    title={"Tutorials"}
                  />

                  <LinkSidebar
                    className={classNames(
                      "__wab_instance",
                      sty.linkSidebar__z9Sc5
                    )}
                    icon={
                      <TrophyIcon
                        className={classNames(projectcss.all, sty.svg__d0Aw1)}
                        role={"img"}
                      />
                    }
                    title={"Sportbooks"}
                  />
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__k2Mxr)}>
                <div className={classNames(projectcss.all, sty.freeBox__oEciv)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__ymzCd
                    )}
                  >
                    {"Live Prices"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__e27Vx
                    )}
                  >
                    {"See all"}
                  </div>
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    sty.freeBox__gRzp8,
                    "bg-grain"
                  )}
                >
                  <div
                    className={classNames(projectcss.all, sty.freeBox___0QPr7)}
                  >
                    <CoinPriceSidebarItem
                      className={classNames(
                        "__wab_instance",
                        sty.coinPriceSidebarItem___1UH4
                      )}
                    />

                    <CoinPriceSidebarItem
                      className={classNames(
                        "__wab_instance",
                        sty.coinPriceSidebarItem__iTjCl
                      )}
                    />

                    <CoinPriceSidebarItem
                      className={classNames(
                        "__wab_instance",
                        sty.coinPriceSidebarItem__wrAs1
                      )}
                    />

                    <CoinPriceSidebarItem
                      className={classNames(
                        "__wab_instance",
                        sty.coinPriceSidebarItem___1DDjA
                      )}
                    />
                  </div>
                </div>
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  sty.freeBox__n4BQj,
                  "bg-grain"
                )}
              >
                <div className={classNames(projectcss.all, sty.freeBox__mzbZs)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__fM6L
                    )}
                  >
                    {"Recent Articles"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__cy45E
                    )}
                  >
                    {"See all"}
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__nUvRo)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__bvstw)}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__sSo1J)}
                      displayHeight={"80px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"80px"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/cryptocasinos/images/placeholder1Jpg.jpg",
                        fullWidth: 2501,
                        fullHeight: 1025,
                        aspectRatio: undefined
                      }}
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        sty.freeBox___1Or48
                      )}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__daQH
                        )}
                      >
                        {"Best mobile crypto casinos in 2026"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__uqcjt
                        )}
                      >
                        {"2 days ago"}
                      </div>
                    </div>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox___0UNig)}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__cw83D)}
                      displayHeight={"80px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"80px"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/cryptocasinos/images/placeholder2Avif.avif",
                        fullWidth: 880,
                        fullHeight: 495,
                        aspectRatio: undefined
                      }}
                    />

                    <div
                      className={classNames(projectcss.all, sty.freeBox__tyhWh)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__tU0Ah
                        )}
                      >
                        {"Why Solana is becoming the gambler's choice"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__w7Q77
                        )}
                      >
                        {"5 days ago"}
                      </div>
                    </div>
                  </div>
                  <div className={classNames(projectcss.all, sty.freeBox__dx6)}>
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__qIyS1)}
                      displayHeight={"80px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"80px"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/cryptocasinos/images/placeholder3Jpg.jpg",
                        fullWidth: 900,
                        fullHeight: 500,
                        aspectRatio: undefined
                      }}
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        sty.freeBox___50ZFb
                      )}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__ygMjt
                        )}
                      >
                        {"Top 5 crypto roulette strategies explained"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__yPmeA
                        )}
                      >
                        {"1 week ago"}
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  sty.freeBox__ncALm,
                  "bg-grain"
                )}
              >
                <div
                  className={classNames(projectcss.all, sty.freeBox__pFio)}
                />

                <div
                  className={classNames(projectcss.all, sty.freeBox___9Yjr2)}
                >
                  <div
                    className={classNames(projectcss.all, sty.freeBox__pJTfk)}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__i3DJf)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"36px"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/cryptocasinos/images/ccIcon.svg",
                        fullWidth: 136.76,
                        fullHeight: 136.76,
                        aspectRatio: 1
                      }}
                    />
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___6PiJ8
                    )}
                  >
                    {"Weekly picks"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__xnuuA
                    )}
                  >
                    {
                      "Get the week's biggest bonus updates, casino launches, and editorial picks in one digest."
                    }
                  </div>
                  <LinkButton
                    className={classNames(
                      "__wab_instance",
                      sty.linkButton___2Swfk
                    )}
                    title={"Subscribe for free"}
                  />
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "coinPriceMarquee",
    "hero",
    "span",
    "content",
    "cardsCasinos",
    "cardPriceChart",
    "sidebar"
  ],

  coinPriceMarquee: ["coinPriceMarquee"],
  hero: ["hero", "span"],
  span: ["span"],
  content: ["content", "cardsCasinos", "cardPriceChart", "sidebar"],
  cardsCasinos: ["cardsCasinos"],
  cardPriceChart: ["cardPriceChart"],
  sidebar: ["sidebar"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicHomepage__ArgProps,
          internalVariantPropNames: PlasmicHomepage__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicHomepage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomepage";
  } else {
    func.displayName = `PlasmicHomepage.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepage = Object.assign(
  // Top-level PlasmicHomepage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    coinPriceMarquee: makeNodeComponent("coinPriceMarquee"),
    hero: makeNodeComponent("hero"),
    span: makeNodeComponent("span"),
    content: makeNodeComponent("content"),
    cardsCasinos: makeNodeComponent("cardsCasinos"),
    cardPriceChart: makeNodeComponent("cardPriceChart"),
    sidebar: makeNodeComponent("sidebar"),
    // Metadata about props expected for PlasmicHomepage
    internalVariantProps: PlasmicHomepage__VariantProps,
    internalArgProps: PlasmicHomepage__ArgProps,
    pageMetadata: generateDynamicMetadata(wrapQueriesWithLoadingProxy({}), {
      pageRoute: "/",
      pagePath: "/",
      params: {},
      query: {}
    })
  }
);

export default PlasmicHomepage;
/* prettier-ignore-end */
