/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 1LHryFzrfagz6s5XszxyaX
// Component: bDT2gFRjoAiP
import * as React from "react";
import Link from "next/link";
import { useRouter } from "next/router";
import {
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  renderPlasmicSlot
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import LinkButton from "../../LinkButton"; // plasmic-import: IXlYPJ9laVnz/component
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: 1LHryFzrfagz6s5XszxyaX/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 1LHryFzrfagz6s5XszxyaX/styleTokensProvider
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic.module.css"; // plasmic-import: 1LHryFzrfagz6s5XszxyaX/projectcss
import sty from "./PlasmicSectionFullwidthArticle.module.css"; // plasmic-import: bDT2gFRjoAiP/css

createPlasmicElementProxy;

export const PlasmicSectionFullwidthArticle__VariantProps = new Array();

export const PlasmicSectionFullwidthArticle__ArgProps = new Array("authorName");

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicSectionFullwidthArticle__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );
  const $props = {
    ...args,
    ...variants
  };
  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const globalVariants = _useGlobalVariants();
  const styleTokensClassNames = _useStyleTokens();
  return (
    <div
      data-plasmic-name={"hero"}
      data-plasmic-override={overrides.hero}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.hero
      )}
    >
      <div className={classNames(projectcss.all, sty.freeBox__uhz8A)}>
        <div className={classNames(projectcss.all, sty.freeBox__ugnF8)}>
          <div className={classNames(projectcss.all, sty.freeBox__wm612)}>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__k1Oq9
              )}
            >
              {"Top Crypto Casinos"}
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text___4EBgf
              )}
            >
              <React.Fragment>
                <React.Fragment>{"The "}</React.Fragment>
                {
                  <span
                    data-plasmic-name={"span"}
                    data-plasmic-override={overrides.span}
                    className={classNames(
                      projectcss.all,
                      projectcss.span,
                      projectcss.__wab_text,
                      projectcss.plasmic_default__inline,
                      sty.span
                    )}
                  >
                    {"Ultimate Guide"}
                  </span>
                }
                <React.Fragment>{" to Crypto Casinos in 2026"}</React.Fragment>
              </React.Fragment>
            </div>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__rgN0W
              )}
            >
              {
                "Discover the safest platforms, the biggest deposit bonuses, and strategies to maximize your crypto holdings while playing online."
              }
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__zSkG3)}>
            <div className={classNames(projectcss.all, sty.freeBox__zUuaQ)}>
              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__lPnn)}
                displayHeight={"auto"}
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"auto"}
                loading={"lazy"}
                src={{
                  src: "/plasmic/cryptocasinos/images/placeholder2Avif.avif",
                  fullWidth: 880,
                  fullHeight: 495,
                  aspectRatio: undefined
                }}
              />
            </div>
          </div>
        </div>
        <div className={classNames(projectcss.all, sty.freeBox___9KWhf)}>
          <div className={classNames(projectcss.all, sty.freeBox___9PQbA)}>
            <LinkButton
              data-plasmic-name={"linkButton"}
              data-plasmic-override={overrides.linkButton}
              className={classNames("__wab_instance", sty.linkButton)}
              href={`/guides/how-to-choose-a-crypto-casino`}
              title={"Read Full Guide"}
            />
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__t5PPn)}>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__dRlWf
              )}
            >
              {"AUTHOR"}
            </div>
            <PlasmicLink__
              data-plasmic-name={"link"}
              data-plasmic-override={overrides.link}
              className={classNames(projectcss.all, projectcss.a, sty.link)}
              component={Link}
              href={`/authors/peter-pragnanda`}
              legacyBehavior={false}
              platform={"nextjs"}
            >
              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__xOaPl)}
                displayHeight={"32px"}
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"32px"}
                loading={"lazy"}
                src={{
                  src: "/plasmic/cryptocasinos/images/uifacesAlienAvatar1Jpg.jpg",
                  fullWidth: 1024,
                  fullHeight: 1024,
                  aspectRatio: undefined
                }}
              />

              <div className={classNames(projectcss.all, sty.freeBox__tf8F1)}>
                <div className={classNames(projectcss.all, sty.freeBox__lsSir)}>
                  {renderPlasmicSlot({
                    defaultContents: "Peter Pragnanda",
                    value: args.authorName,
                    className: classNames(sty.slotTargetAuthorName)
                  })}
                </div>
              </div>
            </PlasmicLink__>
          </div>
        </div>
      </div>
    </div>
  );
}

const PlasmicDescendants = {
  hero: ["hero", "span", "linkButton", "link"],
  span: ["span"],
  linkButton: ["linkButton"],
  link: ["link"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicSectionFullwidthArticle__ArgProps,
          internalVariantPropNames: PlasmicSectionFullwidthArticle__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicSectionFullwidthArticle__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "hero") {
    func.displayName = "PlasmicSectionFullwidthArticle";
  } else {
    func.displayName = `PlasmicSectionFullwidthArticle.${nodeName}`;
  }
  return func;
}

export const PlasmicSectionFullwidthArticle = Object.assign(
  // Top-level PlasmicSectionFullwidthArticle renders the root element
  makeNodeComponent("hero"),
  {
    // Helper components rendering sub-elements
    span: makeNodeComponent("span"),
    linkButton: makeNodeComponent("linkButton"),
    link: makeNodeComponent("link"),
    // Metadata about props expected for PlasmicSectionFullwidthArticle
    internalVariantProps: PlasmicSectionFullwidthArticle__VariantProps,
    internalArgProps: PlasmicSectionFullwidthArticle__ArgProps
  }
);

export default PlasmicSectionFullwidthArticle;
/* prettier-ignore-end */
