/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 1LHryFzrfagz6s5XszxyaX
// Component: 9cwbKxCRtECB
import * as React from "react";
import { useRouter } from "next/router";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  renderPlasmicSlot
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 1LHryFzrfagz6s5XszxyaX/styleTokensProvider
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic.module.css"; // plasmic-import: 1LHryFzrfagz6s5XszxyaX/projectcss
import sty from "./PlasmicLinkSidebar.module.css"; // plasmic-import: 9cwbKxCRtECB/css
import CoinsIcon from "./icons/PlasmicIcon__Coins"; // plasmic-import: YH9P_qiC8MJ-/icon

createPlasmicElementProxy;

export const PlasmicLinkSidebar__VariantProps = new Array();

export const PlasmicLinkSidebar__ArgProps = new Array("icon", "title");

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicLinkSidebar__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );
  const $props = {
    ...args,
    ...variants
  };
  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const styleTokensClassNames = _useStyleTokens();
  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.root
      )}
    >
      {renderPlasmicSlot({
        defaultContents: (
          <CoinsIcon
            className={classNames(projectcss.all, sty.svg__fjTes)}
            role={"img"}
          />
        ),

        value: args.icon
      })}
      {renderPlasmicSlot({
        defaultContents: "Casino Reviews",
        value: args.title,
        className: classNames(sty.slotTargetTitle)
      })}
      <div
        data-plasmic-name={"text"}
        data-plasmic-override={overrides.text}
        className={classNames(projectcss.all, projectcss.__wab_text, sty.text)}
      >
        {"42"}
      </div>
    </div>
  );
}

const PlasmicDescendants = {
  root: ["root", "text"],
  text: ["text"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicLinkSidebar__ArgProps,
          internalVariantPropNames: PlasmicLinkSidebar__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicLinkSidebar__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicLinkSidebar";
  } else {
    func.displayName = `PlasmicLinkSidebar.${nodeName}`;
  }
  return func;
}

export const PlasmicLinkSidebar = Object.assign(
  // Top-level PlasmicLinkSidebar renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    text: makeNodeComponent("text"),
    // Metadata about props expected for PlasmicLinkSidebar
    internalVariantProps: PlasmicLinkSidebar__VariantProps,
    internalArgProps: PlasmicLinkSidebar__ArgProps
  }
);

export default PlasmicLinkSidebar;
/* prettier-ignore-end */
