/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 1LHryFzrfagz6s5XszxyaX
// Component: iOOjtDw_sc94
import * as React from "react";
import { useRouter } from "next/router";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 1LHryFzrfagz6s5XszxyaX/styleTokensProvider
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic.module.css"; // plasmic-import: 1LHryFzrfagz6s5XszxyaX/projectcss
import sty from "./PlasmicRowChangelog.module.css"; // plasmic-import: iOOjtDw_sc94/css

createPlasmicElementProxy;

export const PlasmicRowChangelog__VariantProps = new Array();

export const PlasmicRowChangelog__ArgProps = new Array();

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicRowChangelog__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );
  const $props = {
    ...args,
    ...variants
  };
  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const styleTokensClassNames = _useStyleTokens();
  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.root
      )}
    >
      <div className={classNames(projectcss.all, sty.freeBox__ti2Wd)}>
        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text___4Nb5
          )}
        >
          {"Mar 22, 2026"}
        </div>
      </div>
      <div className={classNames(projectcss.all, sty.freeBox__iIryC)}>
        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text___1If1B
          )}
        >
          {"Enter some text"}
        </div>
        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text__hfkQc
          )}
        >
          {
            "Stake Casino\u00a0 has established itself as the premier destination for cryptocurrency gambling since its launch in 2017. Operating with a Curacao license, it has built an enormous global user base through high-profile sponsorships (including Drake and the Alfa Romeo F1 team), a completely provably fair ecosystem, and an interface that outclasses almost every traditional fiat casino."
          }
        </div>
      </div>
    </div>
  );
}

const PlasmicDescendants = {
  root: ["root"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicRowChangelog__ArgProps,
          internalVariantPropNames: PlasmicRowChangelog__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicRowChangelog__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicRowChangelog";
  } else {
    func.displayName = `PlasmicRowChangelog.${nodeName}`;
  }
  return func;
}

export const PlasmicRowChangelog = Object.assign(
  // Top-level PlasmicRowChangelog renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    // Metadata about props expected for PlasmicRowChangelog
    internalVariantProps: PlasmicRowChangelog__VariantProps,
    internalArgProps: PlasmicRowChangelog__ArgProps
  }
);

export default PlasmicRowChangelog;
/* prettier-ignore-end */
