/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 1LHryFzrfagz6s5XszxyaX
// Component: oroZGFcSE0LK
import * as React from "react";
import Link from "next/link";
import { useRouter } from "next/router";
import {
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  renderPlasmicSlot
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import LinkButton from "../../LinkButton"; // plasmic-import: IXlYPJ9laVnz/component
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 1LHryFzrfagz6s5XszxyaX/styleTokensProvider
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic.module.css"; // plasmic-import: 1LHryFzrfagz6s5XszxyaX/projectcss
import sty from "./PlasmicCardCoinStats.module.css"; // plasmic-import: oroZGFcSE0LK/css

createPlasmicElementProxy;

export const PlasmicCardCoinStats__VariantProps = new Array();

export const PlasmicCardCoinStats__ArgProps = new Array(
  "icon",
  "coinName",
  "coinShorthand",
  "buttonWrap"
);

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicCardCoinStats__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(
    () =>
      Object.assign(
        {
          icon: {
            src: "/plasmic/cryptocasinos/images/bitcoinCircleSvg.svg",
            fullWidth: 64,
            fullHeight: 64,
            aspectRatio: undefined
          }
        },
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );
  const $props = {
    ...args,
    ...variants
  };
  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const styleTokensClassNames = _useStyleTokens();
  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.root,
        "card-grain"
      )}
    >
      <div className={classNames(projectcss.all, sty.freeBox__pUrPc)}>
        <div className={classNames(projectcss.all, sty.freeBox__tuElg)}>
          <PlasmicLink__
            data-plasmic-name={"link"}
            data-plasmic-override={overrides.link}
            className={classNames(projectcss.all, projectcss.a, sty.link)}
            component={Link}
            href={`/coins/btc`}
            legacyBehavior={false}
            platform={"nextjs"}
          >
            <PlasmicImg__
              data-plasmic-name={"img"}
              data-plasmic-override={overrides.img}
              alt={""}
              className={classNames(sty.img)}
              displayHeight={"38px"}
              displayMaxHeight={"none"}
              displayMaxWidth={"100%"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"38px"}
              loading={"lazy"}
              src={args.icon}
            />
          </PlasmicLink__>
          <div className={classNames(projectcss.all, sty.freeBox__s3IvH)}>
            <div className={classNames(projectcss.all, sty.freeBox__rkPpW)}>
              {renderPlasmicSlot({
                defaultContents: "Bitcoin",
                value: args.coinName,
                className: classNames(sty.slotTargetCoinName)
              })}
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__vMfSq
                )}
              >
                {"$68.530,58"}
              </div>
            </div>
            <div className={classNames(projectcss.all, sty.freeBox__v3Na7)}>
              <div className={classNames(projectcss.all, sty.freeBox__tOkmc)}>
                {renderPlasmicSlot({
                  defaultContents: "BTC",
                  value: args.coinShorthand
                })}
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__vD9B
                )}
              >
                {"+2.4%"}
              </div>
            </div>
          </div>
        </div>
      </div>
      <div className={classNames(projectcss.all, sty.freeBox___5OcN0)}>
        <div className={classNames(projectcss.all, sty.freeBox__jp9IQ)}>
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__thfu7
            )}
          >
            {"Speed"}
          </div>
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__rDsm0
            )}
          >
            {"10-30 min"}
          </div>
        </div>
        <div className={classNames(projectcss.all, sty.freeBox__s8It)}>
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text___3YoYt
            )}
          >
            {"Avg fee"}
          </div>
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__xS3Ka
            )}
          >
            {"$3.50"}
          </div>
        </div>
        <div className={classNames(projectcss.all, sty.freeBox__offQf)}>
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text___3YvGo
            )}
          >
            {"Best for"}
          </div>
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__om1Ei
            )}
          >
            {"Trust & Limits"}
          </div>
        </div>
      </div>
      <div className={classNames(projectcss.all, sty.freeBox__qioc3)}>
        <LinkButton
          data-plasmic-name={"linkButton"}
          data-plasmic-override={overrides.linkButton}
          className={classNames("__wab_instance", sty.linkButton)}
          color={"clear"}
          href={`/coins/btc`}
          size={"small"}
          title={"View more"}
        />

        {renderPlasmicSlot({
          defaultContents: (
            <LinkButton
              className={classNames("__wab_instance", sty.linkButton__uce5)}
              size={"small"}
              title={"BTC Casinos"}
            />
          ),

          value: args.buttonWrap
        })}
      </div>
    </div>
  );
}

const PlasmicDescendants = {
  root: ["root", "link", "img", "linkButton"],
  link: ["link", "img"],
  img: ["img"],
  linkButton: ["linkButton"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicCardCoinStats__ArgProps,
          internalVariantPropNames: PlasmicCardCoinStats__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicCardCoinStats__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicCardCoinStats";
  } else {
    func.displayName = `PlasmicCardCoinStats.${nodeName}`;
  }
  return func;
}

export const PlasmicCardCoinStats = Object.assign(
  // Top-level PlasmicCardCoinStats renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    link: makeNodeComponent("link"),
    img: makeNodeComponent("img"),
    linkButton: makeNodeComponent("linkButton"),
    // Metadata about props expected for PlasmicCardCoinStats
    internalVariantProps: PlasmicCardCoinStats__VariantProps,
    internalArgProps: PlasmicCardCoinStats__ArgProps
  }
);

export default PlasmicCardCoinStats;
/* prettier-ignore-end */
