/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 1LHryFzrfagz6s5XszxyaX
import * as React from "react";
import { EmbedCss } from "@plasmicpkgs/plasmic-embed-css";

export default function GlobalContextsProvider(props) {
  const { children, embedCssProps } = props;
  return (
    <EmbedCss
      {...embedCssProps}
      css={
        embedCssProps && "css" in embedCssProps
          ? embedCssProps.css
          : '/* CSS snippet */\n\n\n.button-border::before {\n  content: "";\n  position: absolute;\n  inset: 1px; /* 1px inset */\n  border-radius: 5px;\n  padding: 1px; /* border thickness */\n  background: linear-gradient(180deg, #404A4C, #262D2F);\n  \n  -webkit-mask: \n    linear-gradient(#000 0 0) content-box, \n    linear-gradient(#000 0 0);\n  -webkit-mask-composite: xor;\n          mask-composite: exclude;\n\n  pointer-events: none;\n}\n\n.button-gray::before {\n  content: "";\n  position: absolute;\n  inset: 1px; /* 1px inset */\n  border-radius: 5px;\n  padding: 1px; /* border thickness */\n  background: linear-gradient(180deg, rgba(255, 255, 255, 1), rgba(0, 29, 33, 0));\n  \n  -webkit-mask: \n    linear-gradient(#000 0 0) content-box, \n    linear-gradient(#000 0 0);\n  -webkit-mask-composite: xor;\n          mask-composite: exclude;\n\n  pointer-events: none;\n}'
      }
    >
      {children}
    </EmbedCss>
  );
}
