/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 1LHryFzrfagz6s5XszxyaX
// Component: 90xCi2dO4d5a
import * as React from "react";
import { useRouter } from "next/router";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import LinkTiny from "../../LinkTiny"; // plasmic-import: s_Cz1URrXJSO/component
import CoinPriceSidebarItem from "../../CoinPriceSidebarItem"; // plasmic-import: OXSVHEvZKoQP/component
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 1LHryFzrfagz6s5XszxyaX/styleTokensProvider
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic.module.css"; // plasmic-import: 1LHryFzrfagz6s5XszxyaX/projectcss
import sty from "./PlasmicSidebarLivePrices.module.css"; // plasmic-import: 90xCi2dO4d5a/css

createPlasmicElementProxy;

export const PlasmicSidebarLivePrices__VariantProps = new Array();

export const PlasmicSidebarLivePrices__ArgProps = new Array();

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicSidebarLivePrices__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );
  const $props = {
    ...args,
    ...variants
  };
  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const styleTokensClassNames = _useStyleTokens();
  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.root
      )}
    >
      <div className={classNames(projectcss.all, sty.freeBox__jHMhs)}>
        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text__tMjWj
          )}
        >
          {"Live Prices"}
        </div>
        <LinkTiny
          data-plasmic-name={"linkTiny"}
          data-plasmic-override={overrides.linkTiny}
          className={classNames("__wab_instance", sty.linkTiny)}
        />
      </div>
      <div
        className={classNames(projectcss.all, sty.freeBox__inmOx, "bg-grain")}
      >
        <div className={classNames(projectcss.all, sty.freeBox__tchgu)}>
          <CoinPriceSidebarItem
            className={classNames(
              "__wab_instance",
              sty.coinPriceSidebarItem__wCzx
            )}
            price={"$71,055.48"}
          />

          <CoinPriceSidebarItem
            change={
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__kM
                )}
              >
                {"-5,66%"}
              </div>
            }
            className={classNames(
              "__wab_instance",
              sty.coinPriceSidebarItem__cpOv7
            )}
            handle={
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__ikm01
                )}
              >
                {"ETH"}
              </div>
            }
            icon={{
              src: "/plasmic/cryptocasinos/images/coinEthSvg.svg",
              fullWidth: 225,
              fullHeight: 225,
              aspectRatio: 1
            }}
            price={"$2,184.65"}
            title={"Ethereum"}
          />

          <CoinPriceSidebarItem
            change={
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__i8FwP
                )}
              >
                {"-4,84%"}
              </div>
            }
            className={classNames(
              "__wab_instance",
              sty.coinPriceSidebarItem__svpC
            )}
            handle={"XRP"}
            icon={{
              src: "/plasmic/cryptocasinos/images/coinXrpSvg.svg",
              fullWidth: 225,
              fullHeight: 225,
              aspectRatio: 1
            }}
            price={"$1.4389"}
            title={"XRP"}
          />

          <CoinPriceSidebarItem
            className={classNames(
              "__wab_instance",
              sty.coinPriceSidebarItem__f2C0X
            )}
            handle={"SOL"}
            icon={{
              src: "/plasmic/cryptocasinos/images/coinSolSvg.svg",
              fullWidth: 225,
              fullHeight: 225,
              aspectRatio: 1
            }}
            price={"$88.88"}
            title={"Solana"}
          />

          <CoinPriceSidebarItem
            change={
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___3F2N
                )}
              >
                {"-4,84%"}
              </div>
            }
            className={classNames(
              "__wab_instance",
              sty.coinPriceSidebarItem___71Ok
            )}
            handle={
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__xtSm
                )}
              >
                {"DOT"}
              </div>
            }
            icon={{
              src: "/plasmic/cryptocasinos/images/coinDotSvg.svg",
              fullWidth: 225,
              fullHeight: 225,
              aspectRatio: 1
            }}
            price={"$1.4389"}
            title={"Polkadot"}
          />

          <CoinPriceSidebarItem
            className={classNames(
              "__wab_instance",
              sty.coinPriceSidebarItem__m4Qm5
            )}
            handle={"ADA"}
            icon={{
              src: "/plasmic/cryptocasinos/images/coinAdaSvg.svg",
              fullWidth: 225,
              fullHeight: 225,
              aspectRatio: 1
            }}
            price={"$88.88"}
            title={"Cardano"}
          />
        </div>
      </div>
    </div>
  );
}

const PlasmicDescendants = {
  root: ["root", "linkTiny"],
  linkTiny: ["linkTiny"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicSidebarLivePrices__ArgProps,
          internalVariantPropNames: PlasmicSidebarLivePrices__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicSidebarLivePrices__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicSidebarLivePrices";
  } else {
    func.displayName = `PlasmicSidebarLivePrices.${nodeName}`;
  }
  return func;
}

export const PlasmicSidebarLivePrices = Object.assign(
  // Top-level PlasmicSidebarLivePrices renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    linkTiny: makeNodeComponent("linkTiny"),
    // Metadata about props expected for PlasmicSidebarLivePrices
    internalVariantProps: PlasmicSidebarLivePrices__VariantProps,
    internalArgProps: PlasmicSidebarLivePrices__ArgProps
  }
);

export default PlasmicSidebarLivePrices;
/* prettier-ignore-end */
