/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 1LHryFzrfagz6s5XszxyaX
// Component: ybjzFR7MtVY2
import * as React from "react";
import Head from "next/head";
import { useRouter } from "next/router";
import {
  PlasmicImg as PlasmicImg__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import HeroCardLink from "../../HeroCardLink"; // plasmic-import: QXwWWXLv7dKm/component
import CornerTDivider from "../../CornerTDivider"; // plasmic-import: uVYTGz9cJOUu/component
import CardPriceChart from "../../CardPriceChart"; // plasmic-import: Bygnfqie3Cqa/component
import SectionHeader from "../../SectionHeader"; // plasmic-import: peFiZbBQXNG2/component
import LinkButton from "../../LinkButton"; // plasmic-import: IXlYPJ9laVnz/component
import CardArticleCover from "../../CardArticleCover"; // plasmic-import: zC-Mr2iMn1dL/component
import CardArticleNoCover from "../../CardArticleNoCover"; // plasmic-import: h0trZzJIFxmu/component
import TagPill from "../../TagPill"; // plasmic-import: nn118kQlMOAC/component
import CardCasinoList from "../../CardCasinoList"; // plasmic-import: 6YxcbeY1AF1_/component
import InfoBlockRank from "../../InfoBlockRank"; // plasmic-import: _Cbr6Dwvaf0w/component
import NewsGridItem from "../../NewsGridItem"; // plasmic-import: ftCRKqiLCHeT/component
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: 1LHryFzrfagz6s5XszxyaX/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 1LHryFzrfagz6s5XszxyaX/styleTokensProvider
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic.module.css"; // plasmic-import: 1LHryFzrfagz6s5XszxyaX/projectcss
import sty from "./PlasmicCoinSample.module.css"; // plasmic-import: ybjzFR7MtVY2/css
import TrophyIcon from "./icons/PlasmicIcon__Trophy"; // plasmic-import: I-1KWj6kHo73/icon
import BookIcon from "./icons/PlasmicIcon__Book"; // plasmic-import: h9sLGs5m_Vd1/icon

const emptyProxy = new Proxy(() => "", {
  get(_, prop) {
    return prop === Symbol.toPrimitive ? () => "" : emptyProxy;
  }
});

function wrapQueriesWithLoadingProxy($q) {
  return new Proxy($q, {
    get(target, queryName) {
      const query = target[queryName];
      return !query || query.isLoading || !query.data ? emptyProxy : query;
    }
  });
}

export function generateDynamicMetadata($q, $ctx) {
  return {
    openGraph: {},
    twitter: {
      card: "summary"
    }
  };
}

createPlasmicElementProxy;

export const PlasmicCoinSample__VariantProps = new Array();

export const PlasmicCoinSample__ArgProps = new Array();

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicCoinSample__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );
  const $props = {
    ...args,
    ...variants
  };
  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const globalVariants = _useGlobalVariants();
  const pageMetadata = generateDynamicMetadata(
    wrapQueriesWithLoadingProxy({}),
    $ctx
  );
  const styleTokensClassNames = _useStyleTokens();
  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            styleTokensClassNames,
            sty.root
          )}
        >
          <div
            data-plasmic-name={"hero"}
            data-plasmic-override={overrides.hero}
            className={classNames(projectcss.all, sty.hero)}
          >
            <div className={classNames(projectcss.all, sty.freeBox___1J4Df)}>
              <div className={classNames(projectcss.all, sty.freeBox__oiOgn)}>
                <div className={classNames(projectcss.all, sty.freeBox__xfNkm)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__pUqzJ)}
                  >
                    <PlasmicImg__
                      data-plasmic-name={"img"}
                      data-plasmic-override={overrides.img}
                      alt={""}
                      className={classNames(sty.img)}
                      displayHeight={"48px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"48px"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/cryptocasinos/images/bitcoinCircleSvg.svg",
                        fullWidth: 64,
                        fullHeight: 64,
                        aspectRatio: undefined
                      }}
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__hQiOg
                      )}
                    >
                      {
                        "Bitcoin casinos, BTC guides and the latest news in one place"
                      }
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__tWalq
                      )}
                    >
                      {
                        "Explore our Bitcoin hub for editor-tested BTC casino recommendations, practical guides, recent Bitcoin gambling news."
                      }
                    </div>
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      sty.freeBox__nm9NE,
                      "card-grain"
                    )}
                  >
                    <HeroCardLink
                      className={classNames(
                        "__wab_instance",
                        sty.heroCardLink__wP5Qe
                      )}
                      description={
                        "Compare editor picks, bonuses, coin support, and withdrawal speed."
                      }
                      href={`/casinos`}
                      icon={
                        <TrophyIcon
                          className={classNames(projectcss.all, sty.svg__soxcq)}
                          role={"img"}
                        />
                      }
                      title={"Best BTC Crypto Casinos"}
                    />

                    <CornerTDivider
                      className={classNames(
                        "__wab_instance",
                        sty.cornerTDivider__iqmra
                      )}
                    />

                    <CornerTDivider
                      className={classNames(
                        "__wab_instance",
                        sty.cornerTDivider__tIhl
                      )}
                    />

                    <HeroCardLink
                      className={classNames(
                        "__wab_instance",
                        sty.heroCardLink___1KQ0B
                      )}
                      description={
                        "Learn about wallets, deposits, confirmations, and lower-fee transfers."
                      }
                      icon={
                        <BookIcon
                          className={classNames(projectcss.all, sty.svg__vLpxw)}
                          role={"img"}
                        />
                      }
                      title={"BTC Guides & News"}
                    />
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__mQzRj)}>
                  <CardPriceChart
                    data-plasmic-name={"cardPriceChart"}
                    data-plasmic-override={overrides.cardPriceChart}
                    className={classNames("__wab_instance", sty.cardPriceChart)}
                  />
                </div>
              </div>
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__xvQ0N)} />
          <div
            data-plasmic-name={"content"}
            data-plasmic-override={overrides.content}
            className={classNames(projectcss.all, sty.content)}
          >
            <div className={classNames(projectcss.all, sty.freeBox__gqLmD)}>
              <SectionHeader
                buttons={
                  <LinkButton
                    className={classNames(
                      "__wab_instance",
                      sty.linkButton__lmXgy
                    )}
                    color={"gray"}
                    href={`/news?coins=${"btc"}`}
                    size={"medium"}
                    title={"All BTC News"}
                  />
                }
                className={classNames(
                  "__wab_instance",
                  sty.sectionHeader__dHp2I
                )}
                description={
                  "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent tempus dolor et odio hendrerit dignissim."
                }
                hasButton={true}
                title={"Selected BTC Guides and News"}
              />

              <div className={classNames(projectcss.all, sty.freeBox__opkCp)}>
                <CardArticleCover
                  data-plasmic-name={"cardArticleCover"}
                  data-plasmic-override={overrides.cardArticleCover}
                  className={classNames("__wab_instance", sty.cardArticleCover)}
                />

                <CardArticleNoCover
                  alt={true}
                  category={
                    <TagPill
                      className={classNames(
                        "__wab_instance",
                        sty.tagPill__gSRsj
                      )}
                      title={"News"}
                    />
                  }
                  className={classNames(
                    "__wab_instance",
                    sty.cardArticleNoCover__m9F50
                  )}
                  description={
                    "Operators are adjusting deposit brackets and reworking VIP retention offers."
                  }
                  title={
                    "How to choose a crypto casino: security, bonus value, and withdrawal speed"
                  }
                />

                <CardArticleNoCover
                  alt={true}
                  category={
                    <TagPill
                      className={classNames(
                        "__wab_instance",
                        sty.tagPill__m9Tma
                      )}
                      title={"News"}
                    />
                  }
                  className={classNames(
                    "__wab_instance",
                    sty.cardArticleNoCover__mWjtd
                  )}
                  description={
                    "USDT and USDC continue gaining share among readers seeking lower volatility."
                  }
                  title={"Are stablecoins becoming the preferred payment rail?"}
                />

                <CardArticleNoCover
                  alt={true}
                  category={
                    <TagPill
                      className={classNames(
                        "__wab_instance",
                        sty.tagPill__fGvId
                      )}
                      title={
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__dzVt3
                          )}
                        >
                          {"News"}
                        </div>
                      }
                    />
                  }
                  className={classNames(
                    "__wab_instance",
                    sty.cardArticleNoCover__m1VRz
                  )}
                  description={
                    "USDT and USDC continue gaining share among readers seeking lower volatility."
                  }
                  title={"Are stablecoins becoming the preferred payment rail?"}
                />

                <CardArticleNoCover
                  alt={true}
                  category={
                    <TagPill
                      className={classNames(
                        "__wab_instance",
                        sty.tagPill__onLpE
                      )}
                      title={"News"}
                    />
                  }
                  className={classNames(
                    "__wab_instance",
                    sty.cardArticleNoCover__q2X9E
                  )}
                  description={
                    "USDT and USDC continue gaining share among readers seeking lower volatility."
                  }
                  title={"Are stablecoins becoming the preferred payment rail?"}
                />
              </div>
              <SectionHeader
                buttons={
                  <LinkButton
                    className={classNames(
                      "__wab_instance",
                      sty.linkButton__d5Oe
                    )}
                    color={"gray"}
                    href={`/casinos`}
                    size={"medium"}
                    title={"Explore Top Casinos"}
                  />
                }
                className={classNames(
                  "__wab_instance",
                  sty.sectionHeader__oTiAg
                )}
                description={
                  "Lorem ipsum dolor sit amet, consectetur adipiscing elit. "
                }
                hasButton={true}
                title={"Best Bitcoin casinos accepting BTC right now"}
              />

              <div
                data-plasmic-name={"cardsCasinos"}
                data-plasmic-override={overrides.cardsCasinos}
                className={classNames(projectcss.all, sty.cardsCasinos)}
              >
                <CardCasinoList
                  className={classNames(
                    "__wab_instance",
                    sty.cardCasinoList__hNwk5
                  )}
                  logo={{
                    src: "/plasmic/cryptocasinos/images/roobetLogoSvg.svg",
                    fullWidth: 516.85,
                    fullHeight: 517,
                    aspectRatio: 0.99971
                  }}
                  position={"#2"}
                  title={"Roobet"}
                />

                <CardCasinoList
                  className={classNames(
                    "__wab_instance",
                    sty.cardCasinoList__rpD69
                  )}
                  logo={{
                    src: "/plasmic/cryptocasinos/images/roobetLogoSvg.svg",
                    fullWidth: 516.85,
                    fullHeight: 517,
                    aspectRatio: 0.99971
                  }}
                  position={"#2"}
                  title={"Roobet"}
                />

                <CardCasinoList
                  className={classNames(
                    "__wab_instance",
                    sty.cardCasinoList__oV6Yl
                  )}
                  logo={{
                    src: "/plasmic/cryptocasinos/images/roobetLogoSvg.svg",
                    fullWidth: 516.85,
                    fullHeight: 517,
                    aspectRatio: 0.99971
                  }}
                  position={"#2"}
                  title={"Roobet"}
                />
              </div>
              <InfoBlockRank
                data-plasmic-name={"infoBlockRank"}
                data-plasmic-override={overrides.infoBlockRank}
                className={classNames("__wab_instance", sty.infoBlockRank)}
              />

              <div className={classNames(projectcss.all, sty.freeBox__ndeF)}>
                <SectionHeader
                  buttons={
                    <LinkButton
                      className={classNames(
                        "__wab_instance",
                        sty.linkButton__c38YW
                      )}
                      color={"gray"}
                      href={`/news?coins=${"btc"}`}
                      size={"medium"}
                      title={"All BTC News"}
                    />
                  }
                  className={classNames(
                    "__wab_instance",
                    sty.sectionHeader__wrIr9
                  )}
                  description={
                    "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent tempus dolor et odio hendrerit dignissim."
                  }
                  hasButton={true}
                  title={"BTC News"}
                />

                <div className={classNames(projectcss.all, sty.freeBox__bUDbg)}>
                  <NewsGridItem
                    className={classNames(
                      "__wab_instance",
                      sty.newsGridItem___3YluM
                    )}
                  />

                  <NewsGridItem
                    authorName={"Lana Dubrownik"}
                    autohrAvatar={{
                      src: "/plasmic/cryptocasinos/images/uifacesAlienAvatarJpg.jpg",
                      fullWidth: 1024,
                      fullHeight: 1024,
                      aspectRatio: undefined
                    }}
                    className={classNames(
                      "__wab_instance",
                      sty.newsGridItem__l0SEw
                    )}
                    cover={{
                      src: "/plasmic/cryptocasinos/images/placeholder1Jpg.jpg",
                      fullWidth: 2501,
                      fullHeight: 1025,
                      aspectRatio: undefined
                    }}
                    tags={
                      <React.Fragment>
                        <TagPill
                          className={classNames(
                            "__wab_instance",
                            sty.tagPill___3J4Ok
                          )}
                          title={"Seeds"}
                        />

                        <TagPill
                          className={classNames(
                            "__wab_instance",
                            sty.tagPill__yOuIc
                          )}
                          title={"RTP"}
                        />

                        <TagPill
                          className={classNames(
                            "__wab_instance",
                            sty.tagPill__uwUSf
                          )}
                          title={"BTC"}
                        />
                      </React.Fragment>
                    }
                    title={
                      "How to ensure provably fair gaming at crypto casinos"
                    }
                  />

                  <NewsGridItem
                    authorName={"Lana Dubrownik"}
                    autohrAvatar={{
                      src: "/plasmic/cryptocasinos/images/uifacesAlienAvatarJpg.jpg",
                      fullWidth: 1024,
                      fullHeight: 1024,
                      aspectRatio: undefined
                    }}
                    className={classNames(
                      "__wab_instance",
                      sty.newsGridItem__yzu8Q
                    )}
                    cover={{
                      src: "/plasmic/cryptocasinos/images/placeholder2Avif.avif",
                      fullWidth: 880,
                      fullHeight: 495,
                      aspectRatio: undefined
                    }}
                    tags={
                      <React.Fragment>
                        <TagPill
                          className={classNames(
                            "__wab_instance",
                            sty.tagPill__pnzLy
                          )}
                          title={"Seeds"}
                        />

                        <TagPill
                          className={classNames(
                            "__wab_instance",
                            sty.tagPill__cjdC
                          )}
                          title={"RTP"}
                        />

                        <TagPill
                          className={classNames(
                            "__wab_instance",
                            sty.tagPill__lq9Ia
                          )}
                          title={"BTC"}
                        />
                      </React.Fragment>
                    }
                    title={
                      "How to ensure provably fair gaming at crypto casinos"
                    }
                  />
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__aqgIu)}>
                <SectionHeader
                  buttons={
                    <LinkButton
                      className={classNames(
                        "__wab_instance",
                        sty.linkButton__cdbTb
                      )}
                      color={"gray"}
                      href={`/guides?coins=${"btc"}`}
                      size={"medium"}
                      title={"All BTC Guides"}
                    />
                  }
                  className={classNames(
                    "__wab_instance",
                    sty.sectionHeader___2W6UO
                  )}
                  description={
                    "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent tempus dolor et odio hendrerit dignissim."
                  }
                  hasButton={true}
                  title={"BTC Guides"}
                />

                <div className={classNames(projectcss.all, sty.freeBox__x2Iwk)}>
                  <CardArticleNoCover
                    className={classNames(
                      "__wab_instance",
                      sty.cardArticleNoCover__yeVFp
                    )}
                  />

                  <CardArticleNoCover
                    className={classNames(
                      "__wab_instance",
                      sty.cardArticleNoCover__zwuo2
                    )}
                    description={
                      "Operators are adjusting deposit brackets and reworking VIP retention offers."
                    }
                    title={
                      "How to choose a crypto casino: security, bonus value, and withdrawal speed"
                    }
                  />

                  <CardArticleNoCover
                    className={classNames(
                      "__wab_instance",
                      sty.cardArticleNoCover___57VEt
                    )}
                    description={
                      "Operators are adjusting deposit brackets and reworking VIP retention offers."
                    }
                    title={
                      "How to choose a crypto casino: security, bonus value, and withdrawal speed"
                    }
                  />
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "hero",
    "img",
    "cardPriceChart",
    "content",
    "cardArticleCover",
    "cardsCasinos",
    "infoBlockRank"
  ],

  hero: ["hero", "img", "cardPriceChart"],
  img: ["img"],
  cardPriceChart: ["cardPriceChart"],
  content: ["content", "cardArticleCover", "cardsCasinos", "infoBlockRank"],
  cardArticleCover: ["cardArticleCover"],
  cardsCasinos: ["cardsCasinos"],
  infoBlockRank: ["infoBlockRank"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicCoinSample__ArgProps,
          internalVariantPropNames: PlasmicCoinSample__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicCoinSample__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicCoinSample";
  } else {
    func.displayName = `PlasmicCoinSample.${nodeName}`;
  }
  return func;
}

export const PlasmicCoinSample = Object.assign(
  // Top-level PlasmicCoinSample renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    hero: makeNodeComponent("hero"),
    img: makeNodeComponent("img"),
    cardPriceChart: makeNodeComponent("cardPriceChart"),
    content: makeNodeComponent("content"),
    cardArticleCover: makeNodeComponent("cardArticleCover"),
    cardsCasinos: makeNodeComponent("cardsCasinos"),
    infoBlockRank: makeNodeComponent("infoBlockRank"),
    // Metadata about props expected for PlasmicCoinSample
    internalVariantProps: PlasmicCoinSample__VariantProps,
    internalArgProps: PlasmicCoinSample__ArgProps,
    pageMetadata: generateDynamicMetadata(wrapQueriesWithLoadingProxy({}), {
      pageRoute: "/coins/btc",
      pagePath: "/coins/btc",
      params: {},
      query: {}
    })
  }
);

export default PlasmicCoinSample;
/* prettier-ignore-end */
