/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 1LHryFzrfagz6s5XszxyaX
// Component: h4XyEFfhBuXq
import * as React from "react";
import Link from "next/link";
import { useRouter } from "next/router";
import {
  PlasmicLink as PlasmicLink__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  generateStateOnChangeProp,
  generateStateValueProp,
  useDollarState
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import Tooltip from "../../Tooltip"; // plasmic-import: E5TEWGpV7MnO/component
import LinkCoinIcon from "../../LinkCoinIcon"; // plasmic-import: q2l6s7HIpw7u/component
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 1LHryFzrfagz6s5XszxyaX/styleTokensProvider
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic.module.css"; // plasmic-import: 1LHryFzrfagz6s5XszxyaX/projectcss
import sty from "./PlasmicCardQuickTakeaway.module.css"; // plasmic-import: h4XyEFfhBuXq/css
import CircleQuestionIcon from "./icons/PlasmicIcon__CircleQuestion"; // plasmic-import: nlOIPZUgTjYn/icon

createPlasmicElementProxy;

export const PlasmicCardQuickTakeaway__VariantProps = new Array();

export const PlasmicCardQuickTakeaway__ArgProps = new Array();

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicCardQuickTakeaway__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );
  const $props = {
    ...args,
    ...variants
  };
  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const stateSpecs = React.useMemo(
    () => [
      {
        path: "tooltip.isOpen",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => false
      }
    ],

    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $q: {},
    $refs
  });
  const styleTokensClassNames = _useStyleTokens();
  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.root,
        "card-grain"
      )}
    >
      <div className={classNames(projectcss.all, sty.freeBox__jf1If)}>
        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text__yLn1
          )}
        >
          {"Casino Details"}
        </div>
      </div>
      <div className={classNames(projectcss.all, sty.freeBox__sF4J2)}>
        <div className={classNames(projectcss.all, sty.freeBox__o3Bmp)}>
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__do4Fu
            )}
          >
            {"Website"}
          </div>
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__x25Ez
            )}
          >
            {"stake.com"}
          </div>
        </div>
        <div className={classNames(projectcss.all, sty.freeBox__tGyLl)}>
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__oq6Lu
            )}
          >
            {"Established"}
          </div>
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__tvDd0
            )}
          >
            {"2017"}
          </div>
        </div>
        <div className={classNames(projectcss.all, sty.freeBox___0TuJc)}>
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__aorlf
            )}
          >
            {"License"}
          </div>
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__dkXNo
            )}
          >
            {"Curacao"}
          </div>
        </div>
        <div className={classNames(projectcss.all, sty.freeBox__mznud)}>
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__meWe9
            )}
          >
            {"Owner"}
          </div>
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__a92Dg
            )}
          >
            {"Medium Rare N.V."}
          </div>
        </div>
        <div className={classNames(projectcss.all, sty.freeBox__xTvxw)}>
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__zzEz
            )}
          >
            {"Min Despoit"}
          </div>
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text___1YPyV
            )}
          >
            {"Varies by coin, avg $25"}
          </div>
        </div>
        <div className={classNames(projectcss.all, sty.freeBox__idQ5)}>
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__hyHoi
            )}
          >
            {"KYC Process"}
          </div>
          <div className={classNames(projectcss.all, sty.freeBox___1Xeqj)}>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text___0TfYc
              )}
            >
              {"Level 1 Required"}
            </div>
            <PlasmicLink__
              data-plasmic-name={"link"}
              data-plasmic-override={overrides.link}
              className={classNames(projectcss.all, projectcss.a, sty.link)}
              component={Link}
              href={`/guides/how-to-choose-a-crypto-casino`}
              legacyBehavior={false}
              platform={"nextjs"}
            >
              <Tooltip
                data-plasmic-name={"tooltip"}
                data-plasmic-override={overrides.tooltip}
                className={classNames("__wab_instance", sty.tooltip)}
                content={"Click to learn more"}
                isOpen={generateStateValueProp($state, ["tooltip", "isOpen"])}
                onOpenChange={async (...eventArgs) => {
                  generateStateOnChangeProp($state, [
                    "tooltip",
                    "isOpen"
                  ]).apply(null, eventArgs);
                  if (
                    eventArgs.length > 1 &&
                    eventArgs[1] &&
                    eventArgs[1]._plasmic_state_init_
                  ) {
                    return;
                  }
                }}
                trigger={
                  <CircleQuestionIcon
                    data-plasmic-name={"svg"}
                    data-plasmic-override={overrides.svg}
                    className={classNames(projectcss.all, sty.svg)}
                    role={"img"}
                  />
                }
              />
            </PlasmicLink__>
          </div>
        </div>
        <div className={classNames(projectcss.all, sty.freeBox__ol7P)}>
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__khK8S
            )}
          >
            {"Live Chat"}
          </div>
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__sItD
            )}
          >
            {"Available 24/7"}
          </div>
        </div>
        <div className={classNames(projectcss.all, sty.freeBox__uU2U)}>
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__hJvbs
            )}
          >
            {"Coin support"}
          </div>
          <div
            className={classNames(
              projectcss.all,
              sty.freeBox__jzRkb,
              "link-coin-icon-wrap"
            )}
          >
            <LinkCoinIcon
              className={classNames("__wab_instance", sty.linkCoinIcon__j1CWc)}
              icon={{
                src: "/plasmic/cryptocasinos/images/coinDotSvg.svg",
                fullWidth: 225,
                fullHeight: 225,
                aspectRatio: 1
              }}
            />

            <LinkCoinIcon
              className={classNames("__wab_instance", sty.linkCoinIcon__wypO7)}
              icon={{
                src: "/plasmic/cryptocasinos/images/coinUsdtSvg.svg",
                fullWidth: 225,
                fullHeight: 225,
                aspectRatio: 1
              }}
            />

            <LinkCoinIcon
              className={classNames("__wab_instance", sty.linkCoinIcon__e5AoN)}
              icon={{
                src: "/plasmic/cryptocasinos/images/coinAdaSvg.svg",
                fullWidth: 225,
                fullHeight: 225,
                aspectRatio: 1
              }}
            />

            <LinkCoinIcon
              className={classNames("__wab_instance", sty.linkCoinIcon__u4Fr)}
              icon={{
                src: "/plasmic/cryptocasinos/images/coinEthSvg.svg",
                fullWidth: 225,
                fullHeight: 225,
                aspectRatio: 1
              }}
            />

            <LinkCoinIcon
              className={classNames("__wab_instance", sty.linkCoinIcon__o6SrJ)}
              icon={{
                src: "/plasmic/cryptocasinos/images/coinXrpSvg.svg",
                fullWidth: 225,
                fullHeight: 225,
                aspectRatio: 1
              }}
            />

            <LinkCoinIcon
              className={classNames("__wab_instance", sty.linkCoinIcon___9RaEv)}
              icon={{
                src: "/plasmic/cryptocasinos/images/coinSolSvg.svg",
                fullWidth: 225,
                fullHeight: 225,
                aspectRatio: 1
              }}
            />

            <LinkCoinIcon
              className={classNames("__wab_instance", sty.linkCoinIcon__cjFwx)}
            />
          </div>
        </div>
      </div>
    </div>
  );
}

const PlasmicDescendants = {
  root: ["root", "link", "tooltip", "svg"],
  link: ["link", "tooltip", "svg"],
  tooltip: ["tooltip", "svg"],
  svg: ["svg"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicCardQuickTakeaway__ArgProps,
          internalVariantPropNames: PlasmicCardQuickTakeaway__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicCardQuickTakeaway__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicCardQuickTakeaway";
  } else {
    func.displayName = `PlasmicCardQuickTakeaway.${nodeName}`;
  }
  return func;
}

export const PlasmicCardQuickTakeaway = Object.assign(
  // Top-level PlasmicCardQuickTakeaway renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    link: makeNodeComponent("link"),
    tooltip: makeNodeComponent("tooltip"),
    svg: makeNodeComponent("svg"),
    // Metadata about props expected for PlasmicCardQuickTakeaway
    internalVariantProps: PlasmicCardQuickTakeaway__VariantProps,
    internalArgProps: PlasmicCardQuickTakeaway__ArgProps
  }
);

export default PlasmicCardQuickTakeaway;
/* prettier-ignore-end */
