/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 1LHryFzrfagz6s5XszxyaX
// Component: xAT4KXqPQbaF
import * as React from "react";
import Link from "next/link";
import { useRouter } from "next/router";
import {
  PlasmicLink as PlasmicLink__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  renderPlasmicSlot
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 1LHryFzrfagz6s5XszxyaX/styleTokensProvider
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic.module.css"; // plasmic-import: 1LHryFzrfagz6s5XszxyaX/projectcss
import sty from "./PlasmicNavbarMobileLink.module.css"; // plasmic-import: xAT4KXqPQbaF/css
import BookIcon from "./icons/PlasmicIcon__Book"; // plasmic-import: h9sLGs5m_Vd1/icon

createPlasmicElementProxy;

export const PlasmicNavbarMobileLink__VariantProps = new Array();

export const PlasmicNavbarMobileLink__ArgProps = new Array(
  "href",
  "icon",
  "title"
);

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicNavbarMobileLink__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(
    () =>
      Object.assign(
        {
          href: "#"
        },
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );
  const $props = {
    ...args,
    ...variants
  };
  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const styleTokensClassNames = _useStyleTokens();
  return (
    <PlasmicLink__
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.a,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.root
      )}
      component={Link}
      href={args.href}
      legacyBehavior={false}
      platform={"nextjs"}
    >
      {renderPlasmicSlot({
        defaultContents: (
          <BookIcon
            className={classNames(projectcss.all, sty.svg__wuFjr)}
            role={"img"}
          />
        ),

        value: args.icon,
        className: classNames(sty.slotTargetIcon)
      })}
      {renderPlasmicSlot({
        defaultContents: "Guides",
        value: args.title,
        className: classNames(sty.slotTargetTitle)
      })}
    </PlasmicLink__>
  );
}

const PlasmicDescendants = {
  root: ["root"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicNavbarMobileLink__ArgProps,
          internalVariantPropNames: PlasmicNavbarMobileLink__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicNavbarMobileLink__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicNavbarMobileLink";
  } else {
    func.displayName = `PlasmicNavbarMobileLink.${nodeName}`;
  }
  return func;
}

export const PlasmicNavbarMobileLink = Object.assign(
  // Top-level PlasmicNavbarMobileLink renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    // Metadata about props expected for PlasmicNavbarMobileLink
    internalVariantProps: PlasmicNavbarMobileLink__VariantProps,
    internalArgProps: PlasmicNavbarMobileLink__ArgProps
  }
);

export default PlasmicNavbarMobileLink;
/* prettier-ignore-end */
