/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 1LHryFzrfagz6s5XszxyaX
// Component: s3lR74zcYqTi
import * as React from "react";
import { useRouter } from "next/router";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import LinkButton from "../../LinkButton"; // plasmic-import: IXlYPJ9laVnz/component
import LinkCoinIcon from "../../LinkCoinIcon"; // plasmic-import: q2l6s7HIpw7u/component
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 1LHryFzrfagz6s5XszxyaX/styleTokensProvider
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic.module.css"; // plasmic-import: 1LHryFzrfagz6s5XszxyaX/projectcss
import sty from "./PlasmicActionsMain.module.css"; // plasmic-import: s3lR74zcYqTi/css

createPlasmicElementProxy;

export const PlasmicActionsMain__VariantProps = new Array();

export const PlasmicActionsMain__ArgProps = new Array();

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicActionsMain__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );
  const $props = {
    ...args,
    ...variants
  };
  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const styleTokensClassNames = _useStyleTokens();
  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.root
      )}
    >
      <div
        data-plasmic-name={"wrap"}
        data-plasmic-override={overrides.wrap}
        className={classNames(projectcss.all, sty.wrap)}
      >
        <div className={classNames(projectcss.all, sty.freeBox__rlQ0H)}>
          <LinkButton
            className={classNames("__wab_instance", sty.linkButton__slwX)}
            href={`/casinos`}
          />

          <LinkButton
            className={classNames("__wab_instance", sty.linkButton__ifH8)}
            color={"gray"}
            href={`/guides`}
            title={"Browse Guides"}
          />
        </div>
        <div className={classNames(projectcss.all, sty.freeBox__dwDtG)}>
          <div
            data-plasmic-name={"text"}
            data-plasmic-override={overrides.text}
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text
            )}
          >
            {"Explore Coins"}
          </div>
          <div
            className={classNames(
              projectcss.all,
              sty.freeBox__qRl6A,
              "link-coin-icon-wrap"
            )}
          >
            <LinkCoinIcon
              className={classNames("__wab_instance", sty.linkCoinIcon___2UCr0)}
              icon={{
                src: "/plasmic/cryptocasinos/images/coinDotSvg.svg",
                fullWidth: 225,
                fullHeight: 225,
                aspectRatio: 1
              }}
              shorthand={"DOT"}
            />

            <LinkCoinIcon
              className={classNames("__wab_instance", sty.linkCoinIcon___3I3Qk)}
              icon={{
                src: "/plasmic/cryptocasinos/images/coinUsdtSvg.svg",
                fullWidth: 225,
                fullHeight: 225,
                aspectRatio: 1
              }}
              shorthand={"USDT"}
            />

            <LinkCoinIcon
              className={classNames("__wab_instance", sty.linkCoinIcon__ynLgk)}
              icon={{
                src: "/plasmic/cryptocasinos/images/coinAdaSvg.svg",
                fullWidth: 225,
                fullHeight: 225,
                aspectRatio: 1
              }}
              shorthand={"ADA"}
            />

            <LinkCoinIcon
              className={classNames("__wab_instance", sty.linkCoinIcon__hAj8)}
              icon={{
                src: "/plasmic/cryptocasinos/images/coinEthSvg.svg",
                fullWidth: 225,
                fullHeight: 225,
                aspectRatio: 1
              }}
              shorthand={"ETH"}
            />

            <LinkCoinIcon
              className={classNames("__wab_instance", sty.linkCoinIcon___9KeYk)}
              icon={{
                src: "/plasmic/cryptocasinos/images/coinXrpSvg.svg",
                fullWidth: 225,
                fullHeight: 225,
                aspectRatio: 1
              }}
              shorthand={"XRP"}
            />

            <LinkCoinIcon
              className={classNames("__wab_instance", sty.linkCoinIcon__iuPzt)}
              icon={{
                src: "/plasmic/cryptocasinos/images/coinSolSvg.svg",
                fullWidth: 225,
                fullHeight: 225,
                aspectRatio: 1
              }}
              shorthand={"SOL"}
            />

            <LinkCoinIcon
              className={classNames("__wab_instance", sty.linkCoinIcon__wifyt)}
              shorthand={"BTC"}
            />
          </div>
        </div>
      </div>
    </div>
  );
}

const PlasmicDescendants = {
  root: ["root", "wrap", "text"],
  wrap: ["wrap", "text"],
  text: ["text"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicActionsMain__ArgProps,
          internalVariantPropNames: PlasmicActionsMain__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicActionsMain__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicActionsMain";
  } else {
    func.displayName = `PlasmicActionsMain.${nodeName}`;
  }
  return func;
}

export const PlasmicActionsMain = Object.assign(
  // Top-level PlasmicActionsMain renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    wrap: makeNodeComponent("wrap"),
    text: makeNodeComponent("text"),
    // Metadata about props expected for PlasmicActionsMain
    internalVariantProps: PlasmicActionsMain__VariantProps,
    internalArgProps: PlasmicActionsMain__ArgProps
  }
);

export default PlasmicActionsMain;
/* prettier-ignore-end */
