/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 1LHryFzrfagz6s5XszxyaX
// Component: sfd6F04sxWcM
import * as React from "react";
import Head from "next/head";
import { useRouter } from "next/router";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import LinkButton from "../../LinkButton"; // plasmic-import: IXlYPJ9laVnz/component
import TogglesCoins from "../../TogglesCoins"; // plasmic-import: CJpG2dK0Va9g/component
import NewsGridItem from "../../NewsGridItem"; // plasmic-import: ftCRKqiLCHeT/component
import TagPill from "../../TagPill"; // plasmic-import: nn118kQlMOAC/component
import Pagination from "../../Pagination"; // plasmic-import: pFMQCMqFtkNz/component
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 1LHryFzrfagz6s5XszxyaX/styleTokensProvider
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic.module.css"; // plasmic-import: 1LHryFzrfagz6s5XszxyaX/projectcss
import sty from "./PlasmicSearchResults.module.css"; // plasmic-import: sfd6F04sxWcM/css

const emptyProxy = new Proxy(() => "", {
  get(_, prop) {
    return prop === Symbol.toPrimitive ? () => "" : emptyProxy;
  }
});

function wrapQueriesWithLoadingProxy($q) {
  return new Proxy($q, {
    get(target, queryName) {
      const query = target[queryName];
      return !query || query.isLoading || !query.data ? emptyProxy : query;
    }
  });
}

export function generateDynamicMetadata($q, $ctx) {
  return {
    openGraph: {},
    twitter: {
      card: "summary"
    }
  };
}

createPlasmicElementProxy;

export const PlasmicSearchResults__VariantProps = new Array();

export const PlasmicSearchResults__ArgProps = new Array();

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicSearchResults__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );
  const $props = {
    ...args,
    ...variants
  };
  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const pageMetadata = generateDynamicMetadata(
    wrapQueriesWithLoadingProxy({}),
    $ctx
  );
  const styleTokensClassNames = _useStyleTokens();
  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            styleTokensClassNames,
            sty.root
          )}
        >
          <div className={classNames(projectcss.all, sty.freeBox___0Jz2S)}>
            <div className={classNames(projectcss.all, sty.freeBox__mnCdk)}>
              <div
                data-plasmic-name={"text"}
                data-plasmic-override={overrides.text}
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text
                )}
              >
                {"Search results for"}
              </div>
              <div
                data-plasmic-name={"searchTerm"}
                data-plasmic-override={overrides.searchTerm}
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.searchTerm
                )}
              >
                {"Crypto Casinos"}
              </div>
            </div>
            <div className={classNames(projectcss.all, sty.freeBox__g5Roh)}>
              <div className={classNames(projectcss.all, sty.freeBox__l6Lp6)}>
                <div className={classNames(projectcss.all, sty.freeBox__biBRh)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox___97UBr)}
                  >
                    <LinkButton
                      className={classNames(
                        "__wab_instance",
                        sty.linkButton___5Nhep
                      )}
                      size={"small"}
                      title={"All News"}
                    />

                    <LinkButton
                      className={classNames(
                        "__wab_instance",
                        sty.linkButton__meR4Y
                      )}
                      color={"clear"}
                      size={"small"}
                      title={"No-KYC"}
                    />

                    <LinkButton
                      className={classNames(
                        "__wab_instance",
                        sty.linkButton__truB6
                      )}
                      color={"clear"}
                      size={"small"}
                      title={"Wager-free"}
                    />

                    <LinkButton
                      className={classNames(
                        "__wab_instance",
                        sty.linkButton__ciHo
                      )}
                      color={"clear"}
                      size={"small"}
                      title={"Low fees"}
                    />

                    <LinkButton
                      className={classNames(
                        "__wab_instance",
                        sty.linkButton__p168U
                      )}
                      color={"clear"}
                      size={"small"}
                      title={"Cashback"}
                    />

                    <LinkButton
                      className={classNames(
                        "__wab_instance",
                        sty.linkButton__wkbDy
                      )}
                      color={"clear"}
                      size={"small"}
                      title={"VIP"}
                    />

                    <LinkButton
                      className={classNames(
                        "__wab_instance",
                        sty.linkButton__ktA93
                      )}
                      color={"clear"}
                      size={"small"}
                      title={"RTP"}
                    />

                    <LinkButton
                      className={classNames(
                        "__wab_instance",
                        sty.linkButton__jZyNp
                      )}
                      color={"clear"}
                      size={"small"}
                      title={"Seeds"}
                    />

                    <LinkButton
                      className={classNames(
                        "__wab_instance",
                        sty.linkButton__frD8N
                      )}
                      color={"clear"}
                      size={"small"}
                      title={"Provably fair"}
                    />

                    <LinkButton
                      className={classNames(
                        "__wab_instance",
                        sty.linkButton___0OjN2
                      )}
                      color={"clear"}
                      size={"small"}
                      title={"Licenses"}
                    />

                    <LinkButton
                      className={classNames(
                        "__wab_instance",
                        sty.linkButton__k9R42
                      )}
                      color={"clear"}
                      size={"small"}
                      title={"Bonus terms"}
                    />
                  </div>
                  <TogglesCoins
                    data-plasmic-name={"togglesCoins"}
                    data-plasmic-override={overrides.togglesCoins}
                    className={classNames("__wab_instance", sty.togglesCoins)}
                  />
                </div>
              </div>
            </div>
          </div>
          <div
            data-plasmic-name={"content"}
            data-plasmic-override={overrides.content}
            className={classNames(projectcss.all, sty.content)}
          >
            <div
              data-plasmic-name={"leftContent"}
              data-plasmic-override={overrides.leftContent}
              className={classNames(projectcss.all, sty.leftContent)}
            >
              <div className={classNames(projectcss.all, sty.freeBox__e1VzO)}>
                <NewsGridItem
                  className={classNames(
                    "__wab_instance",
                    sty.newsGridItem__qzc4T
                  )}
                  cover={{
                    src: "/plasmic/cryptocasinos/images/bitcoinJpg.jpg",
                    fullWidth: 1262,
                    fullHeight: 720,
                    aspectRatio: undefined
                  }}
                />

                <NewsGridItem
                  authorName={"Lana Dubrownik"}
                  autohrAvatar={{
                    src: "/plasmic/cryptocasinos/images/uifacesAlienAvatarJpg.jpg",
                    fullWidth: 1024,
                    fullHeight: 1024,
                    aspectRatio: undefined
                  }}
                  className={classNames(
                    "__wab_instance",
                    sty.newsGridItem__iPqlg
                  )}
                  cover={{
                    src: "/plasmic/cryptocasinos/images/placeholder1Jpg.jpg",
                    fullWidth: 2501,
                    fullHeight: 1025,
                    aspectRatio: undefined
                  }}
                  tags={
                    <React.Fragment>
                      <TagPill
                        className={classNames(
                          "__wab_instance",
                          sty.tagPill__eaGkK
                        )}
                        title={"Seeds"}
                      />

                      <TagPill
                        className={classNames(
                          "__wab_instance",
                          sty.tagPill__cvekz
                        )}
                        title={"RTP"}
                      />

                      <TagPill
                        className={classNames(
                          "__wab_instance",
                          sty.tagPill__h8Kke
                        )}
                        title={"BTC"}
                      />
                    </React.Fragment>
                  }
                  title={"How to ensure provably fair gaming at crypto casinos"}
                />

                <NewsGridItem
                  authorName={"Lana Dubrownik"}
                  autohrAvatar={{
                    src: "/plasmic/cryptocasinos/images/uifacesAlienAvatarJpg.jpg",
                    fullWidth: 1024,
                    fullHeight: 1024,
                    aspectRatio: undefined
                  }}
                  className={classNames(
                    "__wab_instance",
                    sty.newsGridItem___01Arr
                  )}
                  cover={{
                    src: "/plasmic/cryptocasinos/images/placeholder2Avif.avif",
                    fullWidth: 880,
                    fullHeight: 495,
                    aspectRatio: undefined
                  }}
                  tags={
                    <React.Fragment>
                      <TagPill
                        className={classNames(
                          "__wab_instance",
                          sty.tagPill__yi1Hz
                        )}
                        title={"Seeds"}
                      />

                      <TagPill
                        className={classNames(
                          "__wab_instance",
                          sty.tagPill__rHKR
                        )}
                        title={"RTP"}
                      />

                      <TagPill
                        className={classNames(
                          "__wab_instance",
                          sty.tagPill__z62Te
                        )}
                        title={"BTC"}
                      />
                    </React.Fragment>
                  }
                  title={"How to ensure provably fair gaming at crypto casinos"}
                />

                <NewsGridItem
                  authorName={"Lana Dubrownik"}
                  autohrAvatar={{
                    src: "/plasmic/cryptocasinos/images/uifacesAlienAvatarJpg.jpg",
                    fullWidth: 1024,
                    fullHeight: 1024,
                    aspectRatio: undefined
                  }}
                  className={classNames(
                    "__wab_instance",
                    sty.newsGridItem__z9Qmb
                  )}
                  cover={{
                    src: "/plasmic/cryptocasinos/images/bitcoinJpg.jpg",
                    fullWidth: 1262,
                    fullHeight: 720,
                    aspectRatio: undefined
                  }}
                  tags={
                    <React.Fragment>
                      <TagPill
                        className={classNames(
                          "__wab_instance",
                          sty.tagPill__x6GrL
                        )}
                        title={"Seeds"}
                      />

                      <TagPill
                        className={classNames(
                          "__wab_instance",
                          sty.tagPill__uvdkG
                        )}
                        title={"RTP"}
                      />

                      <TagPill
                        className={classNames(
                          "__wab_instance",
                          sty.tagPill___1YyA8
                        )}
                        title={"BTC"}
                      />
                    </React.Fragment>
                  }
                  title={"How to ensure provably fair gaming at crypto casinos"}
                />

                <NewsGridItem
                  authorName={"Lana Dubrownik"}
                  autohrAvatar={{
                    src: "/plasmic/cryptocasinos/images/uifacesAlienAvatarJpg.jpg",
                    fullWidth: 1024,
                    fullHeight: 1024,
                    aspectRatio: undefined
                  }}
                  className={classNames(
                    "__wab_instance",
                    sty.newsGridItem__ljjVz
                  )}
                  cover={{
                    src: "/plasmic/cryptocasinos/images/_06CryptoCoverPurpleJpg.jpg",
                    fullWidth: 1600,
                    fullHeight: 675,
                    aspectRatio: undefined
                  }}
                  tags={
                    <React.Fragment>
                      <TagPill
                        className={classNames(
                          "__wab_instance",
                          sty.tagPill__rxMgN
                        )}
                        title={"Seeds"}
                      />

                      <TagPill
                        className={classNames(
                          "__wab_instance",
                          sty.tagPill__fGlCi
                        )}
                        title={"RTP"}
                      />

                      <TagPill
                        className={classNames(
                          "__wab_instance",
                          sty.tagPill__aZyf4
                        )}
                        title={"BTC"}
                      />
                    </React.Fragment>
                  }
                  title={"How to ensure provably fair gaming at crypto casinos"}
                />

                <NewsGridItem
                  authorName={"Lana Dubrownik"}
                  autohrAvatar={{
                    src: "/plasmic/cryptocasinos/images/uifacesAlienAvatarJpg.jpg",
                    fullWidth: 1024,
                    fullHeight: 1024,
                    aspectRatio: undefined
                  }}
                  className={classNames(
                    "__wab_instance",
                    sty.newsGridItem__e98E8
                  )}
                  cover={{
                    src: "/plasmic/cryptocasinos/images/whatIsACryptoProtocol1200X550Svg.svg",
                    fullWidth: 1200,
                    fullHeight: 550,
                    aspectRatio: 2.181818
                  }}
                  tags={
                    <React.Fragment>
                      <TagPill
                        className={classNames(
                          "__wab_instance",
                          sty.tagPill__pz9MQ
                        )}
                        title={"Seeds"}
                      />

                      <TagPill
                        className={classNames(
                          "__wab_instance",
                          sty.tagPill___5Bljh
                        )}
                        title={"RTP"}
                      />

                      <TagPill
                        className={classNames(
                          "__wab_instance",
                          sty.tagPill__k34Gx
                        )}
                        title={"BTC"}
                      />
                    </React.Fragment>
                  }
                  title={"How to ensure provably fair gaming at crypto casinos"}
                />

                <NewsGridItem
                  authorName={"Lana Dubrownik"}
                  autohrAvatar={{
                    src: "/plasmic/cryptocasinos/images/uifacesAlienAvatarJpg.jpg",
                    fullWidth: 1024,
                    fullHeight: 1024,
                    aspectRatio: undefined
                  }}
                  className={classNames(
                    "__wab_instance",
                    sty.newsGridItem__egWUw
                  )}
                  cover={{
                    src: "/plasmic/cryptocasinos/images/placeholder2Avif.avif",
                    fullWidth: 880,
                    fullHeight: 495,
                    aspectRatio: undefined
                  }}
                  tags={
                    <React.Fragment>
                      <TagPill
                        className={classNames(
                          "__wab_instance",
                          sty.tagPill__qNdcd
                        )}
                        title={"Seeds"}
                      />

                      <TagPill
                        className={classNames(
                          "__wab_instance",
                          sty.tagPill__eWivT
                        )}
                        title={"RTP"}
                      />

                      <TagPill
                        className={classNames(
                          "__wab_instance",
                          sty.tagPill__pwlgE
                        )}
                        title={"BTC"}
                      />
                    </React.Fragment>
                  }
                  title={"How to ensure provably fair gaming at crypto casinos"}
                />
              </div>
              <Pagination
                data-plasmic-name={"pagination"}
                data-plasmic-override={overrides.pagination}
                className={classNames("__wab_instance", sty.pagination)}
              />
            </div>
          </div>
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "text",
    "searchTerm",
    "togglesCoins",
    "content",
    "leftContent",
    "pagination"
  ],

  text: ["text"],
  searchTerm: ["searchTerm"],
  togglesCoins: ["togglesCoins"],
  content: ["content", "leftContent", "pagination"],
  leftContent: ["leftContent", "pagination"],
  pagination: ["pagination"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicSearchResults__ArgProps,
          internalVariantPropNames: PlasmicSearchResults__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicSearchResults__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicSearchResults";
  } else {
    func.displayName = `PlasmicSearchResults.${nodeName}`;
  }
  return func;
}

export const PlasmicSearchResults = Object.assign(
  // Top-level PlasmicSearchResults renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    text: makeNodeComponent("text"),
    searchTerm: makeNodeComponent("searchTerm"),
    togglesCoins: makeNodeComponent("togglesCoins"),
    content: makeNodeComponent("content"),
    leftContent: makeNodeComponent("leftContent"),
    pagination: makeNodeComponent("pagination"),
    // Metadata about props expected for PlasmicSearchResults
    internalVariantProps: PlasmicSearchResults__VariantProps,
    internalArgProps: PlasmicSearchResults__ArgProps,
    pageMetadata: generateDynamicMetadata(wrapQueriesWithLoadingProxy({}), {
      pageRoute: "/search",
      pagePath: "/search",
      params: {},
      query: {}
    })
  }
);

export default PlasmicSearchResults;
/* prettier-ignore-end */
