/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 1LHryFzrfagz6s5XszxyaX
// Component: amqWhOAAf6Vm
import * as React from "react";
import { useRouter } from "next/router";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  hasVariant,
  useDollarState
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 1LHryFzrfagz6s5XszxyaX/styleTokensProvider
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic.module.css"; // plasmic-import: 1LHryFzrfagz6s5XszxyaX/projectcss
import sty from "./PlasmicLinkTableOfContentsLast.module.css"; // plasmic-import: amqWhOAAf6Vm/css
import CheckmarkIcon from "./icons/PlasmicIcon__Checkmark"; // plasmic-import: dXFzCG_DnbMq/icon

createPlasmicElementProxy;

export const PlasmicLinkTableOfContentsLast__VariantProps = new Array("isDone");

export const PlasmicLinkTableOfContentsLast__ArgProps = new Array();

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicLinkTableOfContentsLast__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );
  const $props = {
    ...args,
    ...variants
  };
  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const stateSpecs = React.useMemo(
    () => [
      {
        path: "isDone",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => $props.isDone
      }
    ],

    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $q: {},
    $refs
  });
  const styleTokensClassNames = _useStyleTokens();
  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.root,
        { [sty.rootisDone]: hasVariant($state, "isDone", "isDone") }
      )}
    >
      <div
        data-plasmic-name={"freeBox"}
        data-plasmic-override={overrides.freeBox}
        className={classNames(projectcss.all, sty.freeBox, {
          [sty.freeBoxisDone]: hasVariant($state, "isDone", "isDone")
        })}
      >
        <CheckmarkIcon
          data-plasmic-name={"svg"}
          data-plasmic-override={overrides.svg}
          className={classNames(projectcss.all, sty.svg, {
            [sty.svgisDone]: hasVariant($state, "isDone", "isDone")
          })}
          role={"img"}
        />
      </div>
      <div
        data-plasmic-name={"text"}
        data-plasmic-override={overrides.text}
        className={classNames(projectcss.all, projectcss.__wab_text, sty.text, {
          [sty.textisDone]: hasVariant($state, "isDone", "isDone")
        })}
      >
        {"Final takeaway"}
      </div>
    </div>
  );
}

const PlasmicDescendants = {
  root: ["root", "freeBox", "svg", "text"],
  freeBox: ["freeBox", "svg"],
  svg: ["svg"],
  text: ["text"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicLinkTableOfContentsLast__ArgProps,
          internalVariantPropNames: PlasmicLinkTableOfContentsLast__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicLinkTableOfContentsLast__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicLinkTableOfContentsLast";
  } else {
    func.displayName = `PlasmicLinkTableOfContentsLast.${nodeName}`;
  }
  return func;
}

export const PlasmicLinkTableOfContentsLast = Object.assign(
  // Top-level PlasmicLinkTableOfContentsLast renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    freeBox: makeNodeComponent("freeBox"),
    svg: makeNodeComponent("svg"),
    text: makeNodeComponent("text"),
    // Metadata about props expected for PlasmicLinkTableOfContentsLast
    internalVariantProps: PlasmicLinkTableOfContentsLast__VariantProps,
    internalArgProps: PlasmicLinkTableOfContentsLast__ArgProps
  }
);

export default PlasmicLinkTableOfContentsLast;
/* prettier-ignore-end */
