/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 1LHryFzrfagz6s5XszxyaX
// Component: -HNmkPk7FKYK
import * as React from "react";
import { useRouter } from "next/router";
import {
  PlasmicImg as PlasmicImg__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import LinkButton from "../../LinkButton"; // plasmic-import: IXlYPJ9laVnz/component
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 1LHryFzrfagz6s5XszxyaX/styleTokensProvider
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic.module.css"; // plasmic-import: 1LHryFzrfagz6s5XszxyaX/projectcss
import sty from "./PlasmicCardCta.module.css"; // plasmic-import: -HNmkPk7FKYK/css

createPlasmicElementProxy;

export const PlasmicCardCta__VariantProps = new Array();

export const PlasmicCardCta__ArgProps = new Array();

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicCardCta__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );
  const $props = {
    ...args,
    ...variants
  };
  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const styleTokensClassNames = _useStyleTokens();
  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.root,
        "card-grain"
      )}
    >
      <div className={classNames(projectcss.all, sty.freeBox__srh23)}>
        <div className={classNames(projectcss.all, sty.freeBox__o74Up)}>
          <PlasmicImg__
            data-plasmic-name={"img"}
            data-plasmic-override={overrides.img}
            alt={""}
            className={classNames(sty.img)}
            displayHeight={"auto"}
            displayMaxHeight={"none"}
            displayMaxWidth={"none"}
            displayMinHeight={"0"}
            displayMinWidth={"0"}
            displayWidth={"36px"}
            loading={"lazy"}
            src={{
              src: "/plasmic/cryptocasinos/images/ccIcon.svg",
              fullWidth: 136.76,
              fullHeight: 136.76,
              aspectRatio: 1
            }}
          />
        </div>
        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text__kOe5A
          )}
        >
          {"Weekly picks"}
        </div>
        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text__mZa0
          )}
        >
          {
            "Get the week's biggest bonus updates, casino launches, and editorial picks in one digest."
          }
        </div>
        <LinkButton
          data-plasmic-name={"linkButton"}
          data-plasmic-override={overrides.linkButton}
          className={classNames("__wab_instance", sty.linkButton)}
          size={"medium"}
          title={"Subscribe for free"}
        />
      </div>
    </div>
  );
}

const PlasmicDescendants = {
  root: ["root", "img", "linkButton"],
  img: ["img"],
  linkButton: ["linkButton"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicCardCta__ArgProps,
          internalVariantPropNames: PlasmicCardCta__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicCardCta__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicCardCta";
  } else {
    func.displayName = `PlasmicCardCta.${nodeName}`;
  }
  return func;
}

export const PlasmicCardCta = Object.assign(
  // Top-level PlasmicCardCta renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    img: makeNodeComponent("img"),
    linkButton: makeNodeComponent("linkButton"),
    // Metadata about props expected for PlasmicCardCta
    internalVariantProps: PlasmicCardCta__VariantProps,
    internalArgProps: PlasmicCardCta__ArgProps
  }
);

export default PlasmicCardCta;
/* prettier-ignore-end */
